"""Regression guard for the scan core (engines -> rubric -> report).

Runs the real engines against the bundled sample corpus once, then asserts:
  1. exact rule findings on the canonical non-compliant docx (oracle diff),
  2. clean/compliant files score 100 and certify,
  3. malformed files surface as 'error' (never a silent pass),
  4. the safety invariant: an 'error' or 'uncertain' file is NEVER certified,
  5. disabling a rule removes both its findings and its skipped-rule error,
  6. per-engine rule oracles for HTML, XLSX, PPTX, PDF engines.

Synthetic corpus files are generated by scripts/generate_test_corpus.py —
commit the .html/.xlsx/.pptx outputs; the script documents how they were built.

Needs the .NET Office CLI built (spike/dotnet/.../Release) and the PDF engine
deps (api/requirements.txt). Run:  .venv-drive/bin/python -m pytest tests/ -q
"""
from __future__ import annotations
import sys
from pathlib import Path

import pytest

ACP = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ACP / "api"))
sys.path.insert(0, str(ACP / "scripts"))

# The office engine (dotnet + AcpScan.Cli.dll) currently builds only against the
# sibling _review-digital-accessibility checkout, so CI agents can't have it --
# skip the whole module there instead of erroring, LOUDLY, so a green CI run is
# honest about what it did and didn't cover. Locally these always run.
import os as _os
import shutil as _shutil

_DOTNET_OK = _shutil.which("dotnet") or Path(
    _os.environ.get("ACP_DOTNET") or _os.path.expanduser("~/.dotnet/dotnet")).exists()
_CLI_DLL = ACP / "spike/dotnet/AcpScan.Cli/bin/Release/net10.0/AcpScan.Cli.dll"
pytestmark = pytest.mark.skipif(
    not (_DOTNET_OK and _CLI_DLL.exists()),
    reason="office engine unavailable (needs dotnet + AcpScan.Cli.dll built from the "
           "sibling _review-digital-accessibility repo) -- engine oracle tests are "
           "local-only until the engine is vendored/reproducible (see azure-pipelines.yml)")
from scanner import run_scan  # noqa: E402
from rubric import Rubric  # noqa: E402

EXPECTED_DOCX_NONCOMPLIANT = {
    "DOCX-TITLE-001", "DOCX-LANG-001", "DOCX-ALT-001", "DOCX-LINK-001", "DOCX-TABLE-001",
}
CLEAN_COMPLIANT = ["docx-compliant.docx", "pptx-compliant.pptx", "xlsx-compliant.xlsx"]
MALFORMED = ["edge-corrupt.docx", "edge-plaintext.docx", "edge-pdf-as.docx", "pdf-encrypted.pdf"]


@pytest.fixture(scope="module")
def report():
    # scan with the default rubric (ignore any operator-edited rubric.active.json)
    rb = Rubric.load(ACP / "config/rubric.default.json")
    rep = run_scan_default(rb)
    return rep


def run_scan_default(rb: Rubric) -> dict:
    # run_scan resolves the active rubric; for a deterministic baseline we point it
    # at the default by temporarily ensuring no active override is present.
    active = ACP / "config/rubric.active.json"
    saved = active.read_text() if active.exists() else None
    if active.exists():
        active.unlink()
    try:
        return run_scan("local")
    finally:
        if saved is not None:
            active.write_text(saved)


def by_file(report) -> dict:
    return {f["file"]: f for f in report["files"]}


def test_corpus_scanned(report):
    assert report["files"], "no files scanned — is the sample corpus present?"


def test_docx_noncompliant_exact_rules(report):
    f = by_file(report).get("docx-noncompliant.docx")
    assert f is not None and f["status"] == "analysed"
    rules = {i["ruleId"] for i in f["issues"]}
    assert rules == EXPECTED_DOCX_NONCOMPLIANT, f"rule drift: {sorted(rules)}"


def test_clean_files_certify(report):
    bf = by_file(report)
    for name in CLEAN_COMPLIANT:
        f = bf.get(name)
        assert f is not None, f"missing {name}"
        assert f["status"] == "analysed" and f["score"] == 100 and f["compliant"] is True, name


def test_malformed_files_error_not_pass(report):
    bf = by_file(report)
    for name in MALFORMED:
        f = bf.get(name)
        assert f is not None, f"missing {name}"
        assert f["status"] == "error", f"{name} should be 'error', got {f['status']}"


def test_safety_invariant_no_uncertain_or_error_is_certified(report):
    # the product's whole reason to exist: incomplete analysis is never a pass
    for f in report["files"]:
        if f["status"] in ("error", "uncertain"):
            assert f["compliant"] is False, f"{f['file']} certified despite status={f['status']}"
        if f["status"] == "uncertain":
            assert f["score_is_upper_bound"] is True, f["file"]


def test_disabling_a_rule_drops_its_findings_and_errors():
    base = Rubric.load(ACP / "config/rubric.default.json")
    cfg = dict(base.cfg)
    cfg["disabled_rules"] = ["DOCX-TITLE-001"]
    rb = Rubric(cfg)
    a = rb.assess(
        succeeded=True,
        issues=[{"ruleId": "DOCX-TITLE-001", "wcag": "SC_2_4_2", "severity": "SERIOUS"},
                {"ruleId": "DOCX-LANG-001", "wcag": "SC_3_1_1", "severity": "SERIOUS"}],
        errors=[{"message": "boom", "rule": "DOCX-TITLE-001"}],
    )
    # the disabled rule's finding is gone and its error no longer makes the file uncertain
    assert a["status"] == "analysed"
    assert a["skipped_rules"] == 0


# ── HTML engine oracles ──────────────────────────────────────────────────────
# The HTML engine is pure-Python (lxml); oracles are guaranteed to be stable.

def _rules(f: dict) -> set[str]:
    return {i["ruleId"] for i in f["issues"]}


def test_html_missing_title_only(report):
    f = by_file(report).get("html-missing-title.html")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"HTML_MISSING_TITLE"}, f"rule drift: {sorted(_rules(f))}"


def test_html_heading_skip_only(report):
    f = by_file(report).get("html-heading-skip.html")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"HTML_HEADING_SKIP"}, f"rule drift: {sorted(_rules(f))}"


def test_html_all_violations_hits_every_rule(report):
    """html-all-violations.html must trigger all 8 HTML engine rules.

    HTML_LINK_PURPOSE_AMBIGUOUS (2.4.9) added: the fixture's vague link already
    fails 2.4.4 (no context helps a bare "click here") and now also fails 2.4.9
    (the same reasoning applies with zero context credit) — a real, expected hit,
    not test drift to work around.
    """
    ALL_HTML_RULES = {
        "HTML_MISSING_TITLE", "HTML_MISSING_LANG", "HTML_IMG_MISSING_ALT",
        "HTML_EMPTY_LINK", "HTML_VAGUE_LINK", "HTML_HEADING_SKIP", "HTML_INPUT_NO_LABEL",
        "HTML_LINK_PURPOSE_AMBIGUOUS",
    }
    f = by_file(report).get("html-all-violations.html")
    assert f is not None and f["status"] == "analysed"
    assert f["score"] == 0, "file with every rule violated should score 0"
    assert _rules(f) == ALL_HTML_RULES, f"missing rules: {ALL_HTML_RULES - _rules(f)}"


def test_html_critical_existing_rules(report):
    f = by_file(report).get("html-critical-missing-alt.html")
    assert f is not None and f["status"] == "analysed"
    assert f["score"] == 0
    expected = {"HTML_MISSING_LANG", "HTML_IMG_MISSING_ALT", "HTML_VAGUE_LINK", "HTML_INPUT_NO_LABEL"}
    assert expected.issubset(_rules(f)), f"missing: {expected - _rules(f)}"


def test_html_serious_no_lang(report):
    f = by_file(report).get("html-serious-no-lang.html")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"HTML_MISSING_LANG"}, f"rule drift: {sorted(_rules(f))}"


# ── XLSX engine oracles ──────────────────────────────────────────────────────

def test_xlsx_synthetic_violations(report):
    """Synthetic XLSX hits 5 rules: SHEET, MERGE, HIDDEN, TABLE, TITLE, LANG."""
    expected = {"XLSX-SHEET-001", "XLSX-MERGE-001", "XLSX-HIDDEN-001",
                "XLSX-TABLE-001", "XLSX-TITLE-001", "XLSX-LANG-001"}
    f = by_file(report).get("xlsx-synthetic-violations.xlsx")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == expected, f"rule drift: {sorted(_rules(f))}"


def test_xlsx_noncompliant_exact_rules(report):
    f = by_file(report).get("xlsx-noncompliant.xlsx")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"XLSX-TITLE-001", "XLSX-LANG-001"}, f"rule drift: {sorted(_rules(f))}"


# ── PPTX engine oracles ──────────────────────────────────────────────────────

def test_pptx_vague_links(report):
    f = by_file(report).get("pptx-vague-links.pptx")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"PPTX-LINK-001", "PPTX-LANG-001"}, f"rule drift: {sorted(_rules(f))}"


def test_pptx_reading_order(report):
    f = by_file(report).get("pptx-reading-order.pptx")
    assert f is not None and f["status"] == "analysed"
    # Blank layout → no title placeholder → PPTX-TITLE-001 fires in addition
    assert _rules(f) == {"PPTX-ORDER-001", "PPTX-LANG-001", "PPTX-TITLE-001"}, \
        f"rule drift: {sorted(_rules(f))}"


def test_pptx_noncompliant_exact_rules(report):
    f = by_file(report).get("pptx-noncompliant.pptx")
    assert f is not None and f["status"] == "analysed"
    assert _rules(f) == {"PPTX-TITLE-001", "PPTX-ALT-001", "PPTX-LANG-001"}, \
        f"rule drift: {sorted(_rules(f))}"


# ── PDF engine oracles ───────────────────────────────────────────────────────

def test_pdf_titled_lang_rules(report):
    """pdf-titled-lang.pdf has language set, so pdf.document-language should NOT fire."""
    f = by_file(report).get("pdf-titled-lang.pdf")
    assert f is not None and f["status"] == "analysed"
    rules = _rules(f)
    assert "pdf.document-language" not in rules, "pdf-titled-lang.pdf should declare a language"
    assert "pdf.tagged" in rules, "untagged PDF should always fire pdf.tagged"


def test_pdf_clean_accessible_no_language_issues(report):
    """Baseline: pdf-clean-accessible.pdf has the same 3 structural issues as all test PDFs."""
    f = by_file(report).get("pdf-clean-accessible.pdf")
    assert f is not None and f["status"] == "analysed"
    # All current test PDFs are untagged and lack display-doc-title; document-language
    # is present on pdf-titled-lang.pdf but absent here.
    assert "pdf.tagged" in _rules(f)
