"""Helm values are the shared release; the platform only supplies the infrastructure around it.

Kubernetes + Helm is the primary production portability layer, and Azure/AWS/GCP are adapters
around the SAME release. That claim is testable, and these tests are where it is tested: if a
platform could change the application half of the values, the clouds would have forked the
application package — the thing PRD S22 forbids.
"""
from __future__ import annotations

import copy

import pytest

from packaging_helpers import EXAMPLE_IDS, EXAMPLES, load, load_example

# Everything in the values that describes the APPLICATION rather than the infrastructure. These
# keys must be byte-identical across platforms for the same workload.
APPLICATION_KEYS = ("api", "workers", "migrations", "preflight", "networkPolicy")

# Keys the adapter is allowed to change, and the only ones.
ADAPTER_KEYS = ("acpDeployment", "image", "postgresql", "redis", "objectStorage", "secrets",
                "ingress", "observability", "podDisruptionBudget", "ai")


def values(doc):
    from acpctl.values import build_values
    return build_values(doc)


@pytest.mark.parametrize("path", EXAMPLES, ids=EXAMPLE_IDS)
def test_values_render_for_every_profile(path):
    from acpctl.values import render_values_yaml
    text = render_values_yaml(load(path))
    assert "GENERATED by `acpctl values`" in text
    import yaml
    assert yaml.safe_load(text.split("\n", 5)[-1] if False else text)


def test_the_application_half_is_identical_across_every_cloud():
    """The portability claim, asserted directly.

    Same workload, four platforms: only the infrastructure keys may differ.
    """
    base = load_example("standard-production")
    rendered = {}
    for platform, provider, registry in (
        ("azure", "azure-key-vault", "acr.example.org/acp"),
        ("aws", "aws-secrets-manager", "123456789012.dkr.ecr.us-east-1.amazonaws.com/acp"),
        ("gcp", "gcp-secret-manager", "us-docker.pkg.dev/acp/acp"),
        ("kubernetes", "external-secrets", "registry.internal.example.org/acp"),
    ):
        doc = copy.deepcopy(base)
        doc["runtime"]["platform"] = platform
        doc["runtime"]["imageRegistry"] = registry
        doc["secrets"]["provider"] = provider
        rendered[platform] = values(doc)

    reference = rendered["kubernetes"]
    for platform, rendered_values in rendered.items():
        for key in APPLICATION_KEYS:
            assert rendered_values[key] == reference[key], (
                f"platform '{platform}' changed the application half of the release at '{key}'. "
                f"Only the infrastructure adapter may vary between clouds.")


def test_the_adapter_half_does_change_between_clouds():
    """The bite check for the test above.

    If nothing differed between platforms, the identity assertion would be passing vacuously and
    would keep passing after the adapters stopped working.
    """
    doc_a = load_example("standard-production")
    doc_b = copy.deepcopy(doc_a)
    doc_b["runtime"]["platform"] = "kubernetes"
    doc_b["secrets"]["provider"] = "external-secrets"
    a, b = values(doc_a), values(doc_b)
    assert a["secrets"]["externalSecrets"]["backend"] != b["secrets"]["externalSecrets"]["backend"]
    assert a["acpDeployment"]["adapter"] != b["acpDeployment"]["adapter"]
    assert set(ADAPTER_KEYS) & {k for k in a if a[k] != b.get(k)}


def test_managed_data_services_disable_the_in_cluster_subchart():
    """The one structural difference the adapters make: point at the provider, or run it here."""
    managed = values(load_example("standard-production"))
    assert managed["postgresql"]["external"] is True
    assert managed["postgresql"]["enabled"] is False
    assert managed["postgresql"]["chart"] is None

    self_hosted = values(load_example("regulated"))
    assert self_hosted["postgresql"]["external"] is False
    assert self_hosted["postgresql"]["enabled"] is True
    assert self_hosted["postgresql"]["chart"]


def test_queue_signals_select_keda_and_request_signals_select_hpa():
    """PRD S11 prefers queue depth and oldest-job age; CPU lags a batch workload.

    Read on `remediate` rather than `assess`: the example pins assess warm at 5-5 with no
    autoscale block (the owner's 2026-09-05 parity decision), so it has no scaler to select and
    asserting one there would test the fixture rather than the rule.
    """
    rendered = values(load_example("standard-production"))
    assert rendered["workers"]["remediate"]["autoscaling"]["scaler"] == "keda"
    assert rendered["api"]["autoscaling"]["scaler"] == "hpa"


def test_a_pinned_tier_renders_a_fixed_replica_count_and_no_scaler():
    """The other half of the same rule, and the half the parity decision now rests on.

    A tier with no `autoscale` block must render `autoscaling.enabled: false` — that flag is what
    the chart branches on to emit a `ScaledObject`, so a pinned tier that rendered `true` would
    hand a warm pool to KEDA anyway, and the document would still read as pinned.
    """
    rendered = values(load_example("standard-production"))
    assess = rendered["workers"]["assess"]
    assert assess["autoscaling"]["enabled"] is False
    assert "scaler" not in assess["autoscaling"]
    assert assess["replicaCount"] == 5


@pytest.mark.parametrize("path", EXAMPLES, ids=EXAMPLE_IDS)
def test_values_never_pin_a_tag_as_if_it_were_a_digest(path):
    """PRD S5.1: templates reference digests. An empty map is an honest 'not yet resolved'; a
    default would deploy a mutable tag."""
    assert values(load(path))["image"]["digests"] == {}


@pytest.mark.parametrize("path", EXAMPLES, ids=EXAMPLE_IDS)
def test_values_carry_references_and_never_a_secret_value(path):
    import json
    doc = load(path)
    text = json.dumps(values(doc))
    for marker in ("hunter2", "-----BEGIN", "sk-lf-", "password"):
        assert marker not in text
    for name, ref in values(doc)["secrets"]["refs"].items():
        assert set(ref) <= {"name", "key", "version"}, name


@pytest.mark.parametrize("path", EXAMPLES, ids=EXAMPLE_IDS)
def test_network_policy_defaults_to_deny_and_never_admits_workers(path):
    policy = values(load(path))["networkPolicy"]
    assert policy["enabled"] is True
    assert policy["defaultDeny"] is True
    assert policy["workerIngress"] is False


@pytest.mark.parametrize("path", EXAMPLES, ids=EXAMPLE_IDS)
def test_migrations_are_a_pre_deploy_hook_that_must_complete(path):
    """ADR 0045: old code must never be the first thing to meet the new schema."""
    migrations = values(load(path))["migrations"]
    assert migrations["enabled"] is True
    assert "pre-install" in migrations["hook"] and "pre-upgrade" in migrations["hook"]
    assert migrations["backoffLimit"] == 0


def test_worker_env_matches_the_inventory():
    """values and inventory must not derive the tier configuration independently."""
    from acpctl.inventory import build_inventory
    doc = load_example("regulated")
    rendered = values(doc)
    services = {s.name: s for s in build_inventory(doc)}
    for tier, service in (("discover", "acp-discovery"), ("assess", "acp-assess"),
                          ("remediate", "acp-remediate")):
        assert rendered["workers"][tier]["env"] == services[service].env
