import { describe, it, expect } from 'vitest'
import { readdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { modelLabel, visionReady, UNKNOWN_MODEL } from './aiModel.js'

const here = dirname(fileURLToPath(import.meta.url))
const read = (f) => readFileSync(join(here, f), 'utf8')

describe('modelLabel — the model that actually ran', () => {
  it('reports the id the deployment reports', () => {
    const status = { model: 'llama3.2', vision_model: 'llava:7b' }
    expect(modelLabel(status, 'vision')).toBe('llava:7b')
    expect(modelLabel(status, 'text')).toBe('llama3.2')
  })

  it('names no model when the backend has not answered', () => {
    // Guessing a default would claim a model that may not be what's deployed.
    expect(modelLabel(undefined, 'vision')).toBe(UNKNOWN_MODEL)
    expect(modelLabel({}, 'vision')).toBe(UNKNOWN_MODEL)
    expect(modelLabel({ vision_model: '   ' }, 'vision')).toBe(UNKNOWN_MODEL)
    expect(modelLabel({ vision_model: 42 }, 'vision')).toBe(UNKNOWN_MODEL)
  })

  it('UNKNOWN_MODEL names no vendor', () => {
    expect(UNKNOWN_MODEL).not.toMatch(/claude|gpt|anthropic|openai/i)
  })

  it('vision is only promised when a vision model is reachable', () => {
    expect(visionReady({ available: true, vision_available: true })).toBe(true)
    expect(visionReady({ available: true, vision_available: false })).toBe(false)
    expect(visionReady({ available: false, vision_available: true })).toBe(false)
    expect(visionReady(undefined)).toBe(false)
  })
})

// ACP has no Anthropic or OpenAI client anywhere in api/, and nothing transcribes audio.
// The UI nevertheless shipped "⚡ Claude vision", "⚡ Whisper", and — in the certification
// PDF — "Executive summary generated by Claude (Anthropic Opus 4.8)". Naming a model that
// never ran is worse than naming none, and it breaks the local-models-only promise that
// PrivateAiBadge makes on an adjacent screen.
describe('no rendered string names a model the product never calls', () => {
  const VENDOR = /(Claude|Whisper|Anthropic|OpenAI|GPT-\d)/
  // Files allowed to mention a vendor: this file, the module explaining why, the narration
  // guard, the dead Netlify-prototype module (whose comments say so), the badge that promises
  // we DON'T use them, and "Claude-paced" (a statement about who wrote the code, not runtime).
  const EXEMPT = new Set(['aiModel.js', 'aiModel.test.js', 'phaseNarration.js', 'aiRemediate.js',
                          'PrivateAiBadge.jsx', 'evidenceMount.test.js'])

  const sources = readdirSync(here).filter((f) => /\.(js|jsx)$/.test(f) && !EXEMPT.has(f))

  it('checks a meaningful number of files', () => {
    expect(sources.length).toBeGreaterThan(20)
  })

  it.each(sources)('%s names no third-party model in rendered text', (f) => {
    const offending = read(f).split('\n')
      .map((line, i) => [i + 1, line])
      .filter(([, line]) => VENDOR.test(line))
      .filter(([, line]) => !/^\s*(\/\/|\*|\/\*)/.test(line))   // comments may explain the history
      .filter(([, line]) => !/Claude-paced/.test(line))          // who built it, not what runs
    expect(offending.map(([n, l]) => `${f}:${n} ${l.trim()}`)).toEqual([])
  })
})

describe('the certification PDF attributes the real model', () => {
  it('no longer credits Anthropic in any RENDERED line', () => {
    // The comment above the fix quotes the old string on purpose — history is worth keeping.
    // Judge what the report prints: any p.text(...) naming a vendor.
    const rendered = read('pdfReport.js').split('\n').filter((l) => !/^\s*(\/\/|\*)/.test(l))
    expect(rendered.filter((l) => /(Anthropic|Claude|OpenAI|GPT-\d)/.test(l))).toEqual([])
    expect(read('pdfReport.js')).toMatch(/No content was sent to a third-party AI service/)
  })
})
