import { useEffect, useState } from 'react'
import { getRemediationAIDetails } from './api.js'
import './remediation-ai-suggestions.css'

const text = value => value == null || value === '' ? null : typeof value === 'string' ? value : JSON.stringify(value, null, 2)
const records = value => Array.isArray(value) ? value.filter(item => item && typeof item === 'object' && !Array.isArray(item)) : []
const criterion = value => String(value || '').split('/')[0]
const isAI = proposal => !!(proposal.model || proposal.model_call_id || /\bAI\b|model/i.test(proposal.source || ''))

function decision(item) {
  if (item.superseded) return 'Historical item — no longer current'
  if (item.status === 'rejected') return 'Rejected'
  if (item.status === 'skipped') return 'Skipped'
  if (item.applied) return 'Recorded as applied — verification is not shown here'
  if (item.status === 'approved') return 'Approved — completion is not shown here'
  if (item.status === 'pending' || item.status === 'in_review') return 'Awaiting your review'
  return 'Decision details unavailable'
}

function Proposal({ proposal, item, calls, runId }) {
  // An adjacent call for the same file is not evidence that it produced this value.
  const call = calls.find(call => call.id === proposal.model_call_id && call.scan_id === runId && call.file === item.file)
  const model = call?.model || proposal.model
  const cost = call?.cost_usd
  const hasCost = cost !== null && cost !== undefined && cost !== '' && Number.isFinite(Number(cost)) && Number(cost) >= 0
  return <section className="remediation-ai-suggestions__proposal" aria-label="Stored proposed change">
    <div className="remediation-ai-suggestions__comparison">
      <div><h5>Original content</h5><pre>{text(proposal.before) ?? 'Original content unavailable'}</pre></div>
      <div><h5>Proposed change</h5><pre>{text(proposal.proposed_value) ?? 'Generated content unavailable'}</pre></div>
    </div>
    {text(proposal.locator) && <p><strong>Location:</strong> {text(proposal.locator)}</p>}
    <p><strong>Generated by:</strong> {model ? `${call?.provider ? `${call.provider} · ` : ''}${model}` : 'Model details unavailable'}</p>
    {proposal.source && <p><strong>Recorded source:</strong> {text(proposal.source)}</p>}
    {proposal.rationale && <p><strong>Suggestion explanation:</strong> {text(proposal.rationale)}</p>}
    <details><summary>What is recorded about this AI step?</summary>
      {call ? <>
        <p><strong>Recorded at:</strong> {call.ts || 'Time unavailable'}</p>
        <p><strong>Model call:</strong> {call.id}</p>
        <p><strong>Recorded operation:</strong> {call.surface || 'Operation unavailable'}</p>
        {call.reason && <p><strong>Call outcome note:</strong> {text(call.reason)}</p>}
        <p><strong>Call cost:</strong> {hasCost ? `$${Number(cost).toFixed(6)} USD` : 'Cost unavailable'}. A call can cover more than one finding; this is not a per-finding total.</p>
      </> : <p>The exact model call is not available for this saved suggestion. Nearby calls are not used to guess its history.</p>}
      <p>Earlier AI attempts, previous drafts and separate AI reviewer results are unavailable in this view. A generated suggestion is not a verified fix.</p>
    </details>
  </section>
}

export default function RemediationAISuggestions({ runId, scopeFiles, rows = [], providers = {}, filterToRows = false }) {
  const [history, setHistory] = useState(null)
  const [error, setError] = useState(false)
  const scopeKey = scopeFiles === undefined ? null : JSON.stringify([...new Set((Array.isArray(scopeFiles) ? scopeFiles : []).map(file => typeof file === 'string' ? file : file?.file).filter(Boolean))].sort())
  useEffect(() => {
    let current = true
    setHistory(null)
    setError(false)
    if (!runId) return () => { current = false }
    getRemediationAIDetails(runId).then(value => {
      if (current) setHistory({ ...value, runId, scopeKey })
    }).catch(() => { if (current) setError(true) })
    return () => { current = false }
  }, [runId, scopeKey])
  const visible = history?.runId === runId && history?.scopeKey === scopeKey ? history : null
  const scope = scopeKey === null ? null : new Set(JSON.parse(scopeKey))
  const inScope = file => scope === null || scope.has(file)
  const aiRows = records(rows).filter(row => inScope(row.file) && row.origin === 'ai')
  const matchesRow = item => aiRows.some(row => row.file === item.file && criterion(row.rule_id || row.criterion) === criterion(item.rule_id))
  const items = records(visible?.items).filter(item => item.scan_id === runId && inScope(item.file) && (!filterToRows || matchesRow(item)) && (
    records(item.proposals).some(isAI) || aiRows.some(row => row.file === item.file && criterion(row.rule_id || row.criterion) === criterion(item.rule_id))))
  const planned = Object.entries(providers || {}).filter(([key, value]) => ['text', 'vision'].includes(key) && value?.model)
  return <section className="remediation-ai-suggestions" aria-label="Findings and AI details">
    <p>{filterToRows ? 'View saved suggestions matching the chart findings.' : 'View saved suggestions for the selected files.'} Opening these details does not ask AI to generate anything or approve a change.</p>
    <details><summary>Configured models — not completed calls</summary>
      {planned.length ? <ul>{planned.map(([kind, model]) => <li key={kind}>{kind === 'vision' ? 'Images' : 'Text'}: {model.provider ? `${model.provider} · ` : ''}{model.model}</li>)}</ul> : <p>Configured model details unavailable.</p>}
      <p>The complete fallback sequence is not available here. Configuration does not establish which model generated a saved suggestion.</p>
    </details>
    {!runId ? <p>Choose an assessment to view saved suggestions.</p> : error ? <p role="alert">Saved suggestions could not be loaded. Close and reopen these details to try again.</p> : !visible ? <p role="status">Loading saved suggestions…</p> : visible.available === false ? <p>Saved suggestion details unavailable in this environment.</p> : <>
      {visible.callsAvailable === false && <p role="status">Model call details could not be loaded. Saved proposed changes are still shown.</p>}
      <p>Only retained model-call records are available; older call details may be missing.</p>
      <p>Saved review items can group several findings. This list is not a count of extra fixes produced by AI.</p>
      {items.map(item => <article key={item.id} className="remediation-ai-suggestions__item">
        <h4>{item.file}</h4>
        <p><strong>{item.rule_name || item.rule_id || 'Accessibility finding'}</strong> · Rule {item.rule_id || 'unavailable'}</p>
        <p><strong>Current decision:</strong> {decision(item)}</p>
        {item.reviewer_note && <p><strong>Reviewer note:</strong> {text(item.reviewer_note)}</p>}
        {records(item.proposals).length ? records(item.proposals).map((proposal, index) => <Proposal key={index} proposal={proposal} item={item} calls={records(visible.calls)} runId={runId} />) : <p>Generated content unavailable for this review item.</p>}
      </article>)}
      {aiRows.filter(row => !items.some(item => item.file === row.file && criterion(item.rule_id) === criterion(row.rule_id || row.criterion))).map((row, index) => <article key={row.id || index} className="remediation-ai-suggestions__item">
        <h4>{row.file}</h4><p>{row.plain_name || row.rule_name || row.rule_id || row.criterion}</p>
        <p>{row.has_proposal ? 'Generated content unavailable' : 'No suggestion generated yet'}</p>
        <p>AI can try to prepare a proposed change for this issue. A useful suggestion is not guaranteed.</p>
      </article>)}
      {!items.length && !aiRows.length && <p>No saved AI suggestions are available for this selection.</p>}
      <p>Use the existing review workspace to approve, edit or reject current suggestions.</p>
    </>}
  </section>
}
