// GENERATED FILE — do not edit by hand.
//
// Source: docs/rules/*.md  ·  Regenerate: python scripts/gen_rule_details.py
// Guarded by: tests/test_rule_details_sync.py (CI fails on drift)
//
// Per-rule assessment and remediation detail — what ACP actually checks for a criterion, in the
// words an engineer maintains beside the detector. `remediation` is null for rules whose doc has
// no "Fix mode rationale" section; the UI must say nothing there rather than invent it.

export const RULE_DETAILS = {
  "DOCX-ALT-001": {
    title: "Image missing alt text",
    sc: "1.1.1",
    scName: "Non-text Content",
    level: "A",
    severity: "CRITICAL",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/AltTextRule.cs",
    checks: "Every `<w:drawing>` element that contains a `<wp:docPr>` node must have a non-empty `descr` attribute, unless the drawing carries the OOXML decorative extension (`adec:decorative val=\"1\"` in `<wp:docPr>`'s `extLst`) \u2014 the correct way to mark a decorative image in Word, and the mark reviewers use via \"Mark as decorative\".",
    remediation: null,
  },
  "PPTX-ALT-001": {
    title: "Image missing alt text",
    sc: "1.1.1",
    scName: "Non-text Content",
    level: "A",
    severity: "CRITICAL",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/AltTextRule.cs",
    checks: "Every `<pic:pic>`/`<p:pic>` on every slide must have a non-empty `descr` on its `<p:cNvPr>`, unless the shape carries the PowerPoint decorative extension (`adec:decorative val=\"1\"`). NOT checked: charts, SmartArt and grouped-shape internals (separate elements), or the *quality* of the description.",
    remediation: "**auto** \u2014 The engine fills `descr` from a FAITHFUL in-document source, in priority order: the author's own Alt-Text *Title* field, an adjacent \"Figure N:\" caption paragraph (docx only), or a meaningful (non-generic) shape name. Bare-filename or generic `descr` values (\"image.png\") are treated as missing and replaced the same way. Images with no faithful source are left untouched and reported for human review \u2014 invented alt text is worse than none. (AI captioning from image bytes needs a vision model, which the deployed Ollama text model doesn't provide \u2014 this is the honest deterministic subset.) XML-attribute-only change; slides render identically.",
  },
  "XLSX-ALT-001": {
    title: "Image missing alt text",
    sc: "1.1.1",
    scName: "Non-text Content",
    level: "A",
    severity: "CRITICAL",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/AltTextRule.cs",
    checks: "Every image in `xl/drawings/*.xml` must have a non-empty `descr` on its `<xdr:cNvPr>`, unless the drawing carries the OOXML decorative extension (`adec:decorative val=\"1\"` in `<xdr:cNvPr>`'s `extLst`) \u2014 the same shared Office marker Word and PowerPoint use for \"Mark as decorative\". NOT checked: charts (see the chart-specific oracle corpus file \u2014 chart alt lives on the chart part), sparklines, or conditional-format icons.",
    remediation: "**auto** \u2014 The engine fills `descr` from a FAITHFUL in-document source, in priority order: the author's own Alt-Text *Title* field, an adjacent \"Figure N:\" caption paragraph (docx only), or a meaningful (non-generic) shape name. Bare-filename or generic `descr` values (\"image.png\") are treated as missing and replaced the same way. Images with no faithful source are left untouched and reported for human review \u2014 invented alt text is worse than none. (AI captioning from image bytes needs a vision model, which the deployed Ollama text model doesn't provide \u2014 this is the honest deterministic subset.)",
  },
  "pdf.missing-alt-text": {
    title: "Image missing alt text",
    sc: "1.1.1",
    scName: "Non-text Content",
    level: "A",
    severity: "CRITICAL",
    fixMode: "auto",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/image_alt_text.py",
    checks: "Walks the PDF structure tree and finds every `<Figure>` tag. For each one, checks that the tag's `/Alt` attribute is present and non-empty. The check skips figures that are marked as Artifact (decorative) in the tag tree.",
    remediation: null,
  },
  "DOCX-HEAD-001": {
    title: "Heading structure incorrect",
    sc: "1.3.1",
    scName: "Info and Relationships",
    level: "A",
    severity: "MODERATE",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/HeadingStructureRule.cs",
    checks: "The sequence of paragraphs styled `Heading 1..9` must never skip a level going down (H1 \u2192 H3 without an H2 in between). NOT checked: whether heading text is meaningful, whether the document starts at H1, or outline-level overrides applied via direct formatting.",
    remediation: "**auto** \u2014 the engine re-levels the offending heading to the next expected level (H3 under an H1 becomes H2). Style-only change: the text and its visual prominence via the style's formatting adjust together, and re-validation confirms the sequence.",
  },
  "DOCX-TABLE-001": {
    title: "Table has no header row",
    sc: "1.3.1",
    scName: "Info and Relationships",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/TableHeaderRule.cs",
    checks: "Every `<w:tbl>` must have `<w:tblHeader/>` in the row properties of its first row. NOT checked: layout tables (Word has no reliable data-vs-layout marker, so every table is treated as data), multi-row headers, or row-scope headers.",
    remediation: "**auto** \u2014 the engine adds `<w:tblHeader/>` to the first row of each unmarked table. First-row-as-header is the overwhelmingly common case; a wrong guess is visible and harmless (announcements name the wrong row but the data is untouched).",
  },
  "PPTX-TABLE-001": {
    title: "Table has no header row",
    sc: "1.3.1",
    scName: "Info and Relationships",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/TableHeaderRule.cs",
    checks: "Every `<a:tbl>` must have `firstRow=\"1\"` set in its table properties (`<a:tblPr>`), the OOXML marker PowerPoint uses for \"header row\" styling AND semantics. NOT checked: whether the first row actually contains labels, multi-level headers, or tables pasted as images (those fall under PPTX-ALT-001).",
    remediation: "**auto** \u2014 sets `firstRow=\"1\"` on unmarked tables. This can subtly change the table's visual banding (header styling activates), which is the known cosmetic trade-off of the fix.",
  },
  "XLSX-TABLE-001": {
    title: "Data range has no header row",
    sc: "1.3.1",
    scName: "Info and Relationships",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/TableHeaderRule.cs",
    checks: "Every `<table>` part (ListObject) must have `headerRowCount` \u2265 1 (absent defaults to 1 \u2014 explicitly setting 0 is the violation). NOT checked: raw data ranges never formalised as tables \u2014 the rule cannot see data that isn't marked as a table.",
    remediation: "**auto** \u2014 sets `headerRowCount=\"1\"` and, if the first row was data, shifts it into the header slot the way Excel's own \"My table has headers\" toggle does.",
  },
  "pdf.tagged": {
    title: "PDF is not tagged",
    sc: "1.3.1",
    scName: "Info and Relationships",
    level: "A",
    severity: "SERIOUS",
    fixMode: "human-only",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/tagged_pdf.py",
    checks: "Checks two things: 1. The document catalog's `/MarkInfo` dictionary has `Marked = true`. 2. The document has a `/StructTreeRoot` \u2014 i.e. an actual structure (tag) tree exists and is non-empty. A PDF that passes (1) but fails (2) is declared tagged but has no structure \u2014 this is a defective tag implementation and the rule still fires.",
    remediation: null,
  },
  "PPTX-ORDER-001": {
    title: "Reading order undefined",
    sc: "1.3.2",
    scName: "Meaningful Sequence",
    level: "A",
    severity: "SERIOUS",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/ReadingOrderRule.cs",
    checks: "Reads the `<p:sp>` (shape) order in the slide XML and compares it against the visual bounding boxes of each shape. If the XML order does not match a plausible top-to-bottom, left-to-right reading order, the rule fires. A slide where PowerPoint's default \"auto\" tab order is in place (shapes ordered by insertion time, not position) is flagged unless that order happens to match the visual order.",
    remediation: null,
  },
  "XLSX-BLANK-001": {
    title: "Blank worksheet",
    sc: "1.3.2",
    scName: "Meaningful Sequence",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/BlankWorksheetRule.cs",
    checks: "Every visible sheet is checked for live cell content \u2014 actual cell values or formulas, walked cell-by-cell, never the sheet's cached dimension/\"used range\" record (that record reflects the historical maximum extent a writer ever touched and stays inflated even after every cell in it has been cleared). A sheet with no live cell content is still not flagged if it anchors a chart (`GraphicFrame`) or image (`Picture`) \u2014 a chart-only dashboard sheet is not blank. Hidden and very-hidden sheets are skipped entirely: no user ever tabs to one, so a blank hidden sheet has no navigation exposure to flag.",
    remediation: "**human-only** \u2014 the correct fix is either \"delete the sheet\" or \"add the content that was supposed to be there,\" and only the author knows which. The engine can detect emptiness but not intent.",
  },
  "XLSX-HIDDEN-001": {
    title: "Hidden content",
    sc: "1.3.2",
    scName: "Meaningful Sequence",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/HiddenContentRule.cs",
    checks: "Sheets with `state=\"hidden\"`/`veryHidden`, plus hidden rows/columns that contain non-empty cells. NOT checked: zero-height/width rows and columns that are technically visible, filtered-out rows (a view state, not a document state), or whether the hidden content is actually referenced by visible formulas.",
    remediation: "**human-only** \u2014 hiding is often intentional (scratch calculations, config sheets). Only the author knows whether the content should be exposed, deleted, or documented; the engine reports what is hidden and how much of it holds data.",
  },
  "XLSX-MERGE-001": {
    title: "Merged cells break navigation",
    sc: "1.3.2",
    scName: "Meaningful Sequence",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/MergedCellsRule.cs",
    checks: "Finds any `<mergeCell>` elements in the worksheet XML. Merged cells that span more than one row or column are flagged regardless of content.",
    remediation: null,
  },
  "pdf.reading-order": {
    title: "Reading order undefined",
    sc: "1.3.2",
    scName: "Meaningful Sequence",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/reading_order.py",
    checks: "For each page, the sequence of text in the tag tree is compared against the geometric top-to-bottom / column order of the rendered text; large divergences fail. NOT checked: pages without tags (SKIP \u2014 owned by `pdf.tagged`), right-to-left scripts' column conventions, or tables (cell order is legitimately non-geometric).",
    remediation: "**human-only** \u2014 correct order for sidebars, pull quotes and captions is editorial intent; automated re-ordering can silently destroy meaning, so the engine only reports the mismatch score.",
  },
  "DOCX-CONTRAST-001": {
    title: "Insufficient colour contrast",
    sc: "1.4.3",
    scName: "Contrast (Minimum)",
    level: "AA",
    severity: "SERIOUS",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/ColourContrastRule.cs",
    checks: "For every paragraph run that has explicit text colour (`<w:color>`) and background shading (`<w:shd>`), the rule computes the WCAG relative luminance contrast ratio between the foreground and background RGB values. Contrast below 4.5:1 for normal text (below 3:1 for large text \u2265 18pt or 14pt bold) is flagged. Runs that use automatic colour (no `<w:color>`) are not checked \u2014 their contrast depends on the viewer's theme, which is outside the document.",
    remediation: null,
  },
  "PPTX-CONTRAST-001": {
    title: "Insufficient colour contrast",
    sc: "1.4.3",
    scName: "Contrast (Minimum)",
    level: "AA",
    severity: "SERIOUS",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/ColourContrastRule.cs",
    checks: "Resolved text colour (run properties \u2192 placeholder \u2192 layout \u2192 master theme) against the effective slide background must meet 4.5:1 (3:1 for text \u226518pt, or \u226514pt bold). NOT checked: text over photos/gradients (background colour is not computable \u2014 reported as SKIP, not FAIL), WordArt, or text inside embedded objects.",
    remediation: "**human-only** \u2014 recolouring text changes the deck's design system; the right fix might be darkening text, changing the background, or updating the theme. That's a design decision, so the engine only reports the measured ratio.",
  },
  "PPTX-ANIM-001": {
    title: "Animation interferes with reading",
    sc: "2.1.1",
    scName: "Keyboard",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/AnimationOrderRule.cs",
    checks: "The slide's timing tree (`<p:timing>`) is scanned for effects that remove content (exit effects) or reorder it after narration starts. NOT checked: motion-only emphasis effects, transition effects between slides, or flash-rate limits (a separate seizure-safety concern outside this rule).",
    remediation: "**human-only** \u2014 whether an exit animation destroys meaning or is cosmetic depends entirely on the content; the engine can only point at the effect.",
  },
  "DOCX-BOOKMARK-001": {
    title: "Long document has no bookmarks",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "MINOR",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/BookmarksRule.cs",
    checks: "Documents whose page count (from `docProps/app.xml`) exceeds 10 must contain at least one named, non-hidden `<w:bookmarkStart>`. NOT checked: bookmark coverage or placement quality \u2014 one bookmark anywhere satisfies the rule; documents of 10 pages or fewer are exempt.",
    remediation: "**auto** \u2014 the engine creates bookmarks at each Heading 1/Heading 2, named from the heading text. Additive markup; nothing visible changes in print or layout.",
  },
  "DOCX-TITLE-001": {
    title: "Document title not set",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/DocumentTitleRule.cs",
    checks: "`docProps/core.xml` must contain a `<dc:title>` element with non-whitespace text. NOT checked: whether the title is *meaningful* (a title of \"Document1\" passes), and the filename is never treated as a substitute title.",
    remediation: "**auto** \u2014 the engine derives a title from the first Heading 1 (or the first non-empty paragraph) and writes it to `<dc:title>`. Purely additive metadata; no body content changes, so no human review is needed.",
  },
  "PPTX-TITLE-001": {
    title: "Slide title not set",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/SlideTitleRule.cs",
    checks: "Every slide must contain a placeholder of type `title` (or `ctrTitle`) with non-empty text. NOT checked: text boxes styled to look like titles (only real Title placeholders count), uniqueness of titles across slides, or hidden slides.",
    remediation: "**auto** \u2014 the engine inserts a title from the slide's most prominent text (largest top-most text run) into the layout's Title placeholder, or adds an off-slide title when nothing suitable exists \u2014 the standard \"invisible title\" technique.",
  },
  "PPTX-TITLE-002": {
    title: "Slide title duplicates another slide",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "MODERATE",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/SlideTitleUniquenessRule.cs",
    checks: "Every slide's Title placeholder text against every earlier slide's, case-insensitively. NOT checked: whether a title is present at all (PPTX-TITLE-001 owns that) \u2014 this rule only compares titles that already exist and are non-empty.",
    remediation: "**auto** \u2014 appends a disambiguating suffix drawn from the slide's own body content (its first bullet, or a section number) to the second and later occurrences sharing a title \u2014 the same content-derived-rename technique the sheet-uniqueness fixer uses.",
  },
  "XLSX-TABLE-NAME-001": {
    title: "Generic table name",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "MODERATE",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/TableNameRule.cs",
    checks: "A formal table's (ListObject) `DisplayName` against Excel's auto-generated default pattern `Table\\d+`. NOT checked: header-row presence (XLSX-TABLE-001 owns that), or plain data ranges never formalised as tables.",
    remediation: "**auto** \u2014 renames the table from its header row or the sheet's title, mirroring the sheet-rename fixer's approach. Formula references update automatically because Excel tracks table identity, not display text.",
  },
  "XLSX-TITLE-001": {
    title: "Document title not set",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/DocumentTitleRule.cs",
    checks: "`docProps/core.xml` `<dc:title>` must be non-empty \u2014 identical mechanics to DOCX-TITLE-001, applied to the workbook. NOT checked: title quality; sheet names are XLSX-SHEET-001's job.",
    remediation: "**auto** \u2014 derived from the first sheet's name or the most prominent header cell, written to core properties.",
  },
  "pdf.display-doc-title": {
    title: "Viewer not set to show title",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "MODERATE",
    fixMode: "auto",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/display_title.py",
    checks: "`/ViewerPreferences << /DisplayDocTitle true >>` in the catalog. NOT checked: whether a title exists to display \u2014 that is `pdf.document-title`; both must pass for the pair to work.",
    remediation: "**auto** \u2014 a single boolean write on the catalog's viewer preferences.",
  },
  "pdf.document-title": {
    title: "Document title not set",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/document_title.py",
    checks: "A non-empty `/Title` in the `/Info` dictionary or `dc:title` in XMP metadata (either satisfies). NOT checked: title quality, or whether the viewer is configured to *display* it \u2014 that is `pdf.display-doc-title`.",
    remediation: "**auto** \u2014 the engine writes a title derived from the first H1 tag (or first text line) into both `/Info` and XMP.",
  },
  "pdf.missing-bookmarks": {
    title: "No navigation bookmarks",
    sc: "2.4.2",
    scName: "Page Titled",
    level: "A",
    severity: "MINOR",
    fixMode: "auto",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/bookmarks.py",
    checks: "Documents with more than one page must have an `/Outlines` tree containing at least one entry. NOT checked: outline depth/coverage, whether entries target valid destinations, or single-page documents (exempt).",
    remediation: "**auto** \u2014 the engine builds an outline from H1/H2 tags with page destinations. Additive: no page content changes.",
  },
  "DOCX-LINK-001": {
    title: "Link text not descriptive",
    sc: "2.4.4",
    scName: "Link Purpose (In Context)",
    level: "A",
    severity: "MODERATE",
    fixMode: "ai-assisted",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/LinkPurposeRule.cs",
    checks: "The display text of every `<w:hyperlink>` is tested against a deny-list of generic phrases (click here, read more, more, link, this page\u2026) and a bare-URL pattern. NOT checked: whether descriptive text actually matches the destination, or repeated identical link texts pointing at different targets.",
    remediation: "**ai-assisted** \u2014 the engine drafts replacement text from the destination URL and surrounding sentence, but wording is judgment (\"2026 benefits enrollment form\" vs \"HR portal\"), so the draft routes to the HITL queue for sign-off before it's applied.",
  },
  "PPTX-LINK-001": {
    title: "Link text not descriptive",
    sc: "2.4.4",
    scName: "Link Purpose (In Context)",
    level: "A",
    severity: "MODERATE",
    fixMode: "ai-assisted",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/LinkPurposeRule.cs",
    checks: "Display text of hyperlink runs (`<a:hlinkClick>`) against the same generic-phrase deny-list and bare-URL pattern as DOCX-LINK-001. NOT checked: destination validity, or shape-level links whose \"text\" is the shape's alt text.",
    remediation: "**ai-assisted** \u2014 drafted replacement text goes to the HITL queue; wording on a slide is even more editorially sensitive than in a document.",
  },
  "XLSX-LINK-001": {
    title: "Link text not descriptive",
    sc: "2.4.4",
    scName: "Link Purpose (In Context)",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/LinkPurposeRule.cs",
    checks: "Two distinct hyperlink mechanisms, both against the same deny-list of generic phrases (click here, read more, more, link, this link, url\u2026) plus a raw-URL check (`http://`, `https://`, `www.`): 1. **Standard cell hyperlinks** (Insert \u2192 Link) \u2014 read from the worksheet's own `<hyperlinks>` element, display text resolved from the linked cell's actual value. 2. **Formula-driven links** \u2014 `=HYPERLINK(url, [friendly_name])` cells. These never appear in the worksheet's `<hyperlinks>` element at all \u2014 a detector that only reads that element (or only `cell.hyperlink` in openpyxl) misses every formula-based link entirely. Detected by matching `HYPERLINK(` in the cell's formula text, with the display text read from the cell's own cached value (the friendly name if given, otherwise the URL Excel displays by default). Deliberately not re-parsing the formula's arguments for the pass/fail decision \u2014 only for a best-effort evidence URL \u2014 since formula text can nest quotes and cell references in ways a regex can't reliably unpack.",
    remediation: "**human-only** \u2014 no automated remediation is wired for this rule yet. DOCX and PPTX's link-purpose rule has an AI-assisted drafting lane (destination + surrounding context \u2192 a proposed replacement, human-approved before it's written); XLSX doesn't have that lane built. Don't claim `ai-assisted` here until it is \u2014 this cell only detects.",
  },
  "XLSX-SHEET-001": {
    title: "Generic sheet name",
    sc: "2.4.6",
    scName: "Headings and Labels",
    level: "AA",
    severity: "MODERATE",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/SheetNameRule.cs",
    checks: "Worksheet names against the default-name pattern `Sheet\\d+` (and localized equivalents the engine knows). NOT checked: name quality beyond non-default (a sheet named \"x\" passes), or hidden sheets (XLSX-HIDDEN-001 owns those).",
    remediation: "**auto** \u2014 renames the sheet from its most prominent content (title cell / table name), e.g. \"Sheet2\" \u2192 \"Q3 Budget\". References update automatically because Excel formulas track sheet identity, not display text \u2014 but see failure modes.",
  },
  "XLSX-SHEET-002": {
    title: "Sheet name duplicates another sheet",
    sc: "2.4.6",
    scName: "Headings and Labels",
    level: "AA",
    severity: "MODERATE",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/SheetNameUniquenessRule.cs",
    checks: "Sheet names across the whole workbook for case-insensitive duplicates. NOT checked: whether a name matches Excel's generic default pattern (XLSX-SHEET-001 owns that) \u2014 two custom, non-default names that happen to collide still fire here.",
    remediation: "**auto** \u2014 appends a disambiguating suffix drawn from the sheet's own content (a date, region, or table name found on it) to the second and later occurrences, the same content-derived-rename technique XLSX-SHEET-001's fixer uses.",
  },
  "DOCX-LANG-001": {
    title: "Document language not declared",
    sc: "3.1.1",
    scName: "Language of Page",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/DocumentLanguageRule.cs",
    checks: "`word/settings.xml` (`<w:themeFontLang>`) or the default run properties in `word/styles.xml` must declare a BCP 47 primary language (`<w:lang w:val>`). NOT checked: whether the declared language matches the actual body text, or per-run language overrides (that is DOCX-LANGPART-001).",
    remediation: "**auto** \u2014 the engine detects the dominant script of the body text and writes the matching `w:lang` value. Deterministic metadata write; a wrong auto-detection is caught at re-validation.",
  },
  "DOCX-LANGPART-001": {
    title: "Language of parts not set",
    sc: "3.1.1",
    scName: "Language of Page",
    level: "A",
    severity: "MODERATE",
    fixMode: "human-only",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Docx/Rules/LanguageOfPartsRule.cs",
    checks: "Runs whose text script clearly differs from the document's primary language must carry their own `<w:lang>` override. NOT checked: same-script language switches (English \u2192 Dutch is undetectable without dictionaries), or single foreign words shorter than the detector's minimum span.",
    remediation: "**human-only** \u2014 deciding what is genuinely another language versus a proper noun, product name, or quotation is a judgment call; script-based detection drafts nothing safe enough to auto-apply.",
  },
  "PPTX-LANG-001": {
    title: "Document language not declared",
    sc: "3.1.1",
    scName: "Language of Page",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Pptx/Rules/DocumentLanguageRule.cs",
    checks: "The presentation's default text properties (`ppt/presentation.xml` `defaultTextStyle`) or core properties must declare a BCP 47 language. NOT checked: per-run language overrides on individual slides, or whether the declaration matches the actual text.",
    remediation: "**auto** \u2014 dominant-script detection writes the language into the default text style. Deterministic metadata write.",
  },
  "XLSX-LANG-001": {
    title: "Document language not declared",
    sc: "3.1.1",
    scName: "Language of Page",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "digital-accessibility/DigitalA11y.Analysers.DotNet/Xlsx/Rules/DocumentLanguageRule.cs",
    checks: "A declared language for the workbook's default text \u2014 read from the theme/styles parts. NOT checked: per-cell language (OOXML spreadsheets have no per-cell language model worth checking), or declaration-vs-content mismatch.",
    remediation: "**auto** \u2014 dominant-script detection over cell text, written once at workbook level.",
  },
  "pdf.document-language": {
    title: "Document language not declared",
    sc: "3.1.1",
    scName: "Language of Page",
    level: "A",
    severity: "SERIOUS",
    fixMode: "auto",
    source: "deploy/public/vendor/worker-python/analysers/rules/pdf/document_language.py",
    checks: "A `/Lang` entry with a plausible BCP 47 code in the document catalog. NOT checked: span-level `/Lang` overrides inside the tag tree, or declaration-vs-content match.",
    remediation: "**auto** \u2014 dominant-script detection over extracted text writes `/Lang` on the catalog.",
  },
}

// criterion → the rule ids that implement it, so a per-SC panel can list them.
export const RULES_BY_SC = {
  "1.1.1": ["DOCX-ALT-001", "PPTX-ALT-001", "XLSX-ALT-001", "pdf.missing-alt-text"],
  "1.3.1": ["DOCX-HEAD-001", "DOCX-TABLE-001", "PPTX-TABLE-001", "XLSX-TABLE-001", "pdf.tagged"],
  "1.3.2": ["PPTX-ORDER-001", "XLSX-BLANK-001", "XLSX-HIDDEN-001", "XLSX-MERGE-001", "pdf.reading-order"],
  "1.4.3": ["DOCX-CONTRAST-001", "PPTX-CONTRAST-001"],
  "2.1.1": ["PPTX-ANIM-001"],
  "2.4.2": ["DOCX-BOOKMARK-001", "DOCX-TITLE-001", "PPTX-TITLE-001", "PPTX-TITLE-002", "XLSX-TABLE-NAME-001", "XLSX-TITLE-001", "pdf.display-doc-title", "pdf.document-title", "pdf.missing-bookmarks"],
  "2.4.4": ["DOCX-LINK-001", "PPTX-LINK-001", "XLSX-LINK-001"],
  "2.4.6": ["XLSX-SHEET-001", "XLSX-SHEET-002"],
  "3.1.1": ["DOCX-LANG-001", "DOCX-LANGPART-001", "PPTX-LANG-001", "XLSX-LANG-001", "pdf.document-language"],
}

// The criteria Mova iO tracks (column G) — 17 of the 20-check document core.
// Defined in api/assessment_policy.py:MOVA_TRACKED; see there for how it
// relates to the other four totals this product quotes.
export const TRACKED_17 = new Set(["1.1.1", "1.3.1", "1.3.2", "1.3.3", "1.4.1", "1.4.3", "1.4.5", "1.4.11", "2.1.1", "2.1.2", "2.4.2", "2.4.3", "2.4.4", "2.4.6", "3.1.1", "3.1.2", "4.1.2"])
