#!/usr/bin/env python3
"""Generate the Azure rebuild document and its report from deploy/public/.

PRD §21 phase 3 asks to "rebuild the current Azure deployment using the common contract". Slice 1
compared production to the standard-production EXAMPLE and reported the differences. This asks the
prior question — can the contract DESCRIBE what production runs at all? — and answers it by
deriving the document and running the contract's own validator over it.

TWO ARTIFACTS, ONE DERIVATION, so they cannot disagree:

  packaging/docs/azure-current.acp-deployment.yaml   the document, runnable through acpctl
  packaging/docs/azure-rebuild.md                    the verdict, the budget, and what it could
                                                     not express (generated below the markers)

Both come from `acpctl.azure_document.derive`, which reads the parsed scripts. Change a replica
range in rightsize-production.sh and both regenerate, or `--check` fails.

Usage:
    python scripts/gen_azure_rebuild.py            # rewrite both artifacts
    python scripts/gen_azure_rebuild.py --stdout   # print the report block, write nothing
    python scripts/gen_azure_rebuild.py --check    # CI: fail if either is out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
sys.path.insert(0, str(PACKAGING / "cli"))

DOCUMENT = PACKAGING / "docs" / "azure-current.acp-deployment.yaml"
REPORT = PACKAGING / "docs" / "azure-rebuild.md"
BEGIN = "<!-- BEGIN GENERATED: azure-rebuild"
END = "<!-- END GENERATED: azure-rebuild -->"

# The release the derived document is written against. The scripts do not state a version — they
# deploy whatever image the pipeline built — so this is the CLI's own default rather than a fact
# read from deploy/public/, and the report says so.
VERSION = "2026.9"

HEADER = """\
# Today's Azure deployment, as a deployment document.
#
# GENERATED by scripts/gen_azure_rebuild.py from deploy/public/*.sh. Do not edit by hand: edit the
# scripts, or the generator, and regenerate.
#
# THIS DESCRIBES WHAT PRODUCTION RUNS, NOT WHAT IT SHOULD RUN. The replica ranges, the pinned
# connection pools and the single-replica API floor are today's configuration, faithfully. Whether
# to change any of them is the decision packaging/docs/azure-parity.md puts to the owner; this
# file deliberately takes no position on it.
#
# IT DOES NOT VALIDATE CLEANLY, AND THAT IS THE REPORT. See packaging/docs/azure-rebuild.md for
# each remaining error and why it is a fact about the deployment rather than about this file.
"""


def _derived():
    from acpctl.azure_document import derive
    return derive(version=VERSION)


def render_document() -> str:
    import yaml
    doc = _derived()
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=100,
                          allow_unicode=True)
    return HEADER + body


def build() -> str:
    from acpctl.azure_document import NOT_EXPRESSIBLE
    from acpctl.inventory import build_inventory, connection_budget
    from acpctl.spec import validate

    doc = _derived()
    result = validate(doc)
    budget = connection_budget(doc)

    lines: list[str] = []
    lines.append("_Generated by `scripts/gen_azure_rebuild.py` from `deploy/public/*.sh`. "
                 "Do not edit by hand._")
    lines.append("")

    lines.append("## The document")
    lines.append("")
    lines.append(f"`{DOCUMENT.relative_to(ROOT)}` — derived from the same parse, so the two "
                 "cannot disagree.")
    lines.append("")

    lines.append("## Does it validate?")
    lines.append("")
    verdict = ("**Yes** — the contract describes today's Azure with nothing left over."
               if not result.errors else
               f"**No — {len(result.errors)} error(s).** Each one below is a fact about the "
               f"deployment or about `deploy/public/`, not about the derivation.")
    lines.append(verdict)
    lines.append("")
    if result.errors:
        # `acpctl values` refuses a document with errors, so this is not a paperwork failure: it
        # is the reason the chart cannot be pointed at today's Azure yet, and it is worth saying
        # in the generated half where it stays true rather than in prose that could go stale.
        lines.append("`acpctl values` refuses a document with errors, so **the chart cannot yet "
                     "render a release that reproduces today's Azure** — not because the workload "
                     "is inexpressible, but because the deployment does not satisfy the profile "
                     "it runs under. Clear the two rows below and the render succeeds; the "
                     "connection pools, the queue-depth scaler on remediate and the private "
                     "worker posture all carry through.")
        lines.append("")
        lines.append("| Field | Error |")
        lines.append("|---|---|")
        for f in result.errors:
            lines.append(f"| `{f.path}` | {f.message} |")
        lines.append("")
    if result.warnings:
        lines.append(f"{len(result.warnings)} warning(s):")
        lines.append("")
        for f in result.warnings:
            lines.append(f"- `{f.path}` — {f.message}")
        lines.append("")

    lines.append("## Postgres connections")
    lines.append("")
    lines.append("Worst case at max replicas, against the server production actually runs.")
    lines.append("")
    lines.append("| Service | Replicas | Pool per replica | Worst case |")
    lines.append("|---|---|---:|---:|")
    for service in build_inventory(doc):
        if not service.db_connections_max or not service.replicas:
            continue
        lo, hi = service.replicas
        per = service.db_connections_max // hi
        pinned = " (pinned)" if service.env.get("ACP_DB_MAX_CONN") else " (derived)"
        lines.append(f"| `{service.name}` | {lo}–{hi} | {per}{pinned} | "
                     f"{service.db_connections_max} |")
    lines.append(f"| **total** | | | **{budget['worstCaseConnections']}** |")
    lines.append("")
    lines.append(f"Against `maxConnections: {budget['serverMaxConnections']}` — "
                 f"**{'within' if budget['withinBudget'] else 'OVER'} budget**, "
                 f"headroom {budget['headroom']}.")
    lines.append("")

    lines.append("## What the contract could not express")
    lines.append("")
    lines.append("Fields this document states differently from the deployment, or leaves "
                 "unstated, with why.")
    lines.append("")
    for field, why in sorted(NOT_EXPRESSIBLE.items()):
        lines.append(f"- **`{field}`** — {why}")
    lines.append("")

    lines.append("## What this cannot see")
    lines.append("")
    lines.append("Everything above is what the SCRIPTS configure. The same three blind spots as "
                 "`azure-parity.md`: discovery's scale rule (applied outside this repository), "
                 "`ACP_WORKER_ROLE` on assess and remediate (set outside these scripts), and any "
                 "change made by hand in the portal.")
    lines.append("")
    lines.append(f"The release is recorded as `{VERSION}` because `deploy/public/` deploys "
                 "whatever image the pipeline built and states no version — that one value is the "
                 "CLI's default, not a fact read from the scripts.")
    lines.append("")
    return "\n".join(lines)


def splice(block: str) -> tuple[str, bool]:
    text = REPORT.read_text()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit(
            f"{REPORT.name}: markers not found. Add\n  {BEGIN} -->\n  {END}\n"
            f"around the generated section first.")
    head = text[i:text.index("-->", i) + 4]
    new = f"{head}\n\n{block}\n"
    return text[:i] + new + text[j:], text[i:j] != new


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print the block, write nothing")
    ap.add_argument("--check", action="store_true", help="fail if either artifact is out of date")
    args = ap.parse_args()

    block = build()
    document = render_document()
    if args.stdout:
        print(block)
        return 0

    text, report_changed = splice(block)
    document_changed = not DOCUMENT.exists() or DOCUMENT.read_text() != document

    if args.check:
        stale = [p.relative_to(ROOT) for p, changed in
                 ((REPORT, report_changed), (DOCUMENT, document_changed)) if changed]
        if stale:
            print(f"STALE: {', '.join(str(p) for p in stale)} — run "
                  f"`python scripts/gen_azure_rebuild.py` and commit the result.", file=sys.stderr)
            return 1
        print("packaging/docs/azure-rebuild.md and azure-current.acp-deployment.yaml are current")
        return 0

    if not report_changed and not document_changed:
        print("azure rebuild unchanged")
        return 0
    if report_changed:
        REPORT.write_text(text)
        print(f"regenerated {REPORT.relative_to(ROOT)}")
    if document_changed:
        DOCUMENT.write_text(document)
        print(f"regenerated {DOCUMENT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
