#!/usr/bin/env python3
"""Generate packaging/docs/service-inventory.md from the deployment documents themselves.

WHY GENERATED. The question this document answers — "what does an ACP installation consist of, at
each profile?" — is a fact about the contract, not a decision about the work. Hand-written, it
goes stale in the one direction that matters: it keeps describing a tier, a secret or a
dependency that the contract has since changed, and it reads as current the whole time. This repo
has already paid for that (docs/TODO.md carried coverage facts 387 commits out of date, and the
stalest part was the headline).

The split, matching scripts/gen_todo_status.py:

  DERIVED (here)   services, images, roles, replica ranges, sizes, ingress posture, secret
                   references, dependencies and the connection budget, per profile.
  AUTHORED (there) why a profile exists, what is supported versus preview, and what to do about
                   it. Not derivable, and no generator should pretend.

Usage:
    python scripts/gen_service_inventory.py            # rewrite the generated block
    python scripts/gen_service_inventory.py --stdout   # print it, write nothing
    python scripts/gen_service_inventory.py --check    # CI: fail if the file is out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
sys.path.insert(0, str(PACKAGING / "cli"))

TARGET = PACKAGING / "docs" / "service-inventory.md"
BEGIN = "<!-- BEGIN GENERATED: service-inventory"
END = "<!-- END GENERATED: service-inventory -->"


def _examples() -> list[Path]:
    return sorted((PACKAGING / "examples").glob("*.acp-deployment.yaml"))


def build() -> str:
    from acpctl import presets
    from acpctl.inventory import build_inventory, connection_budget
    from acpctl.spec import load_document, validate

    lines: list[str] = []
    lines.append("_Generated by `scripts/gen_service_inventory.py` from "
                 "`packaging/examples/*.acp-deployment.yaml`. Do not edit by hand._")
    lines.append("")
    lines.append("## Platform support")
    lines.append("")
    lines.append("| Platform | Adapter supplies | Status |")
    lines.append("|---|---|---|")
    for platform in sorted(presets.SUPPORT_STATUS):
        lines.append(f"| `{platform}` | {presets.PLATFORM_ADAPTER[platform]} | "
                     f"**{presets.SUPPORT_STATUS[platform]}** |")
    lines.append("")
    lines.append("`supported` means a reference deployment in this repository runs the contract "
                 "suite against it. Everything else is `planned`.")
    lines.append("")

    lines.append("## Resource presets")
    lines.append("")
    lines.append("| Preset | CPU | Memory | Temporary storage | Worker threads/replica |")
    lines.append("|---|---:|---:|---:|---:|")
    for name, row in presets.PRESETS.items():
        from acpctl.inventory import worker_threads
        lines.append(f"| {name} | {row['cpu']} | {row['memory']} | {row['ephemeralStorage']} | "
                     f"{worker_threads(name)} |")
    lines.append("")

    for path in _examples():
        doc = load_document(path)
        result = validate(doc)
        rt = doc["runtime"]
        lines.append(f"## Profile: {rt['profile']} (`{path.name}`)")
        lines.append("")
        lines.append(f"Platform `{rt['platform']}` · release `{rt['version']}` · "
                     f"{'VALID' if result.ok else 'INVALID'}"
                     f"{'' if result.ok else ' — ' + '; '.join(f.rule for f in result.errors)}")
        lines.append("")
        lines.append("| Service | Kind | Provisioning | Ingress | Replicas | CPU/Memory | "
                     "Role | Secret references |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for s in build_inventory(doc):
            replicas = f"{s.replicas[0]}–{s.replicas[1]}" if s.replicas else "—"
            size = f"{s.resources['cpu']}/{s.resources['memory']}" if s.resources else "—"
            refs = ", ".join(f"`{r}`" for r in s.secret_refs) or "—"
            lines.append(f"| `{s.name}` | {s.kind} | {s.provisioning} | {s.ingress} | "
                         f"{replicas} | {size} | {s.role or '—'} | {refs} |")
        budget = connection_budget(doc)
        lines.append("")
        lines.append(f"Postgres connections at maximum replicas: "
                     f"**{budget['worstCaseConnections']}** of {budget['serverMaxConnections']} "
                     f"({budget['headroom']} spare).")
        if result.warnings:
            lines.append("")
            for warning in result.warnings:
                lines.append(f"> ⚠ {warning.message}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def splice(block: str) -> tuple[str, bool]:
    text = TARGET.read_text()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit(
            f"{TARGET.name}: markers not found. Add\n  {BEGIN} -->\n  {END}\n"
            f"around the generated section first.")
    head = text[i:text.index("-->", i) + 4]
    new = f"{head}\n\n{block}\n"
    return text[:i] + new + text[j:], text[i:j] != new


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print the block, write nothing")
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    block = build()
    if args.stdout:
        print(block)
        return 0

    text, changed = splice(block)
    if args.check:
        if changed:
            print("packaging/docs/service-inventory.md is STALE — run "
                  "`python scripts/gen_service_inventory.py` and commit the result.",
                  file=sys.stderr)
            return 1
        print("packaging/docs/service-inventory.md is current")
        return 0
    if not changed:
        print("service inventory unchanged")
        return 0
    TARGET.write_text(text)
    print(f"regenerated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
