#!/usr/bin/env python3
"""Generate packaging/docs/azure-adapter.md — what the Azure adapter must provision.

PRD §21 phase 3 asks to rebuild Azure on the common contract and to add managed-service and
private-network options. Slice 1 wrote down what production runs; slice 2 derived a document that
describes it. Neither says who MAKES a document true — and slice 2 shipped a declaration
(`secrets.workloadIdentity`) with no owner at all, which is the shape of gap this table closes.

Generated across every example plus the derived azure-current document, because the interesting
requirements are the ones that DIFFER between them: a self-hosted Postgres asks the adapter for
nothing, an embedded one asks for less than that, and only a document with a workload identity
asks for the three resources that make one real.

Usage:
    python scripts/gen_azure_adapter.py            # rewrite the generated block
    python scripts/gen_azure_adapter.py --stdout   # print it, write nothing
    python scripts/gen_azure_adapter.py --check    # CI: fail if the file is out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
sys.path.insert(0, str(PACKAGING / "cli"))

TARGET = PACKAGING / "docs" / "azure-adapter.md"
BEGIN = "<!-- BEGIN GENERATED: azure-adapter"
END = "<!-- END GENERATED: azure-adapter -->"

# The derived description of production comes first: it is the document the adapter has to satisfy
# to reach parity, and the others are there to show what changes when the document does.
PRIMARY = PACKAGING / "docs" / "azure-current.acp-deployment.yaml"


def _documents() -> list[tuple[str, Path]]:
    from acpctl.spec import load_document
    rows = [("azure-current (derived from production)", PRIMARY)]
    for path in sorted((PACKAGING / "examples").glob("*.acp-deployment.yaml")):
        rows.append((path.name.replace(".acp-deployment.yaml", ""), path))
    # Only azure documents: the adapter is Azure's, and AWS/GCP are phase 4. Filtering here rather
    # than rendering an empty section keeps the table about what exists.
    return [(name, p) for name, p in rows
            if load_document(p)["runtime"]["platform"] == "azure"]


def build() -> str:
    from acpctl.adapter_azure import UNOWNED, VENDOR, report
    from acpctl.spec import load_document

    lines: list[str] = []
    lines.append("_Generated by `scripts/gen_azure_adapter.py` from the deployment documents in "
                 "`packaging/`. Do not edit by hand._")
    lines.append("")

    documents = _documents()
    lines.append("## Requirements per document")
    lines.append("")
    lines.append("Only documents that declare `platform: azure` — the adapter is Azure's, and "
                 "AWS/GCP are phase 4.")
    lines.append("")

    for name, path in documents:
        doc = load_document(path)
        rep = report(doc)
        lines.append(f"### `{name}`")
        lines.append("")
        lines.append(f"Profile `{doc['runtime']['profile']}`, "
                     f"postgres `{doc['data']['postgres']['mode']}`, "
                     f"{len(rep.requirements)} requirements.")
        lines.append("")
        lines.append("| Resource | Setting | Required | From | Why |")
        lines.append("|---|---|---|---|---|")
        for r in rep.requirements:
            value = str(r.value).replace("|", "\\|")
            why = r.because.replace("|", "\\|").replace("\n", " ")
            lines.append(f"| `{r.resource}` | `{r.setting}` | {value} | {r.source} | {why} |")
        lines.append("")
        if rep.undecided:
            lines.append(f"**{len(rep.undecided)} UNDECIDED** — a setting the adapter must choose "
                         "and this document does not state.")
            lines.append("")
        if rep.conflicts:
            lines.append(f"**{len(rep.conflicts)} conflict(s)** between the document's own "
                         "numbers and what the adapter would have to build.")
            lines.append("")

    lines.append("## Requirements this repository cannot verify")
    lines.append("")
    lines.append("Marked `vendor` above: they rest on an Azure fact that cannot be checked from "
                 "here offline, so the requirement states the condition to satisfy rather than a "
                 "value that would read as confirmed.")
    lines.append("")
    seen: dict[str, str] = {}
    for _name, path in documents:
        for r in report(load_document(path)).requirements:
            if r.source == VENDOR:
                seen.setdefault(f"{r.resource}.{r.setting}", r.because)
    for key, why in sorted(seen.items()):
        lines.append(f"- **`{key}`** — {why}")
    lines.append("")

    lines.append("## Not expressed by the contract at all")
    lines.append("")
    lines.append("Settings the adapter must decide that no deployment document carries. Named "
                 "because an adapter author reading only the tables above would otherwise "
                 "conclude the list is complete.")
    lines.append("")
    for what, why in sorted(UNOWNED.items()):
        lines.append(f"- **{what}** — {why}")
    lines.append("")
    return "\n".join(lines)


def splice(block: str) -> tuple[str, bool]:
    text = TARGET.read_text()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit(
            f"{TARGET.name}: markers not found. Add\n  {BEGIN} -->\n  {END}\n"
            f"around the generated section first.")
    head = text[i:text.index("-->", i) + 4]
    new = f"{head}\n\n{block}\n"
    return text[:i] + new + text[j:], text[i:j] != new


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print the block, write nothing")
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    block = build()
    if args.stdout:
        print(block)
        return 0

    text, changed = splice(block)
    if args.check:
        if changed:
            print("packaging/docs/azure-adapter.md is STALE — run "
                  "`python scripts/gen_azure_adapter.py` and commit the result.", file=sys.stderr)
            return 1
        print("packaging/docs/azure-adapter.md is current")
        return 0
    if not changed:
        print("azure adapter unchanged")
        return 0
    TARGET.write_text(text)
    print(f"regenerated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
