#!/usr/bin/env python3
"""Generate packaging/docs/azure-parity.md from deploy/public/ and the contract.

WHY GENERATED. PRD §21 phase 3 asks for proof of parity between the running Azure deployment and
the common contract. A hand-written comparison is true on the day it is written and silently wrong
afterwards — and `deploy/public/` is actively edited by other work, so "afterwards" can be the
same afternoon. Deriving it means the document cannot disagree with the scripts: change a replica
range in `rightsize-production.sh` and either this regenerates or `--check` fails.

The split, matching gen_service_inventory.py:

  DERIVED (here)   what each container app is configured with, what the contract describes, and
                   every field where the two differ.
  AUTHORED (in the file, above the markers)  what to DO about each difference. Whether Azure
                   should adopt the contract's autoscaling or the contract should record Azure's
                   pinned-warm model is a decision, and no generator should pretend to make it.

Usage:
    python scripts/gen_azure_parity.py            # rewrite the generated block
    python scripts/gen_azure_parity.py --stdout   # print it, write nothing
    python scripts/gen_azure_parity.py --check    # CI: fail if the file is out of date
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
sys.path.insert(0, str(PACKAGING / "cli"))

TARGET = PACKAGING / "docs" / "azure-parity.md"
BEGIN = "<!-- BEGIN GENERATED: azure-parity"
END = "<!-- END GENERATED: azure-parity -->"


def build() -> str:
    from acpctl.azure_baseline import OUT_OF_SCOPE
    from acpctl.azure_parity import ACKNOWLEDGED, DIVERGENCE, compare

    report = compare()
    lines: list[str] = []
    lines.append("_Generated by `scripts/gen_azure_parity.py` from `deploy/public/*.sh` and "
                 "`packaging/examples/standard-production.acp-deployment.yaml`. "
                 "Do not edit by hand._")
    lines.append("")

    lines.append("## What Azure actually runs")
    lines.append("")
    lines.append("Parsed from the deployment scripts, not from a live subscription.")
    lines.append("")
    lines.append("| Container app | Tier | CPU | Memory | Replicas | DB pool | Scales? | "
                 "Ingress | Scale rules | Read from |")
    lines.append("|---|---|---:|---:|---|---:|---|---|---|---|")
    for name, app in report["apps"].items():
        tier = f"`{app.tier}`" if app.tier else "—"
        replicas = (f"{app.min_replicas}–{app.max_replicas}"
                    if app.min_replicas is not None else "—")
        rules = ", ".join(f"`{r}`" for r in app.scale_rules) or "none in this repo"
        # ACP_DB_MAX_CONN, where one is pinned. Shown beside the replica range because the two
        # are one fact: a 5-10 replica ceiling is a 20-connection budget once the pool is 2.
        pool = app.db_pool if app.db_pool is not None else "—"
        lines.append(
            f"| `{name}` | {tier} | {app.cpu if app.cpu is not None else '—'} | "
            f"{app.memory or '—'} | {replicas} | {pool} | "
            f"{'yes' if app.autoscaled else '**no**'} | "
            f"{app.ingress or 'none'} | {rules} | {app.source} |")
    lines.append("")

    lines.append("## What the contract describes")
    lines.append("")
    lines.append("| Tier | CPU | Memory | Replicas | Autoscaled |")
    lines.append("|---|---:|---:|---|---|")
    for tier, want in sorted(report["contract"].items()):
        lines.append(f"| `{tier}` | {want['cpu']} | {want['memory']} | "
                     f"{want['replicas.min']}–{want['replicas.max']} | "
                     f"{'yes' if want['autoscaled'] else 'no'} |")
    lines.append("")

    lines.append("## Differences")
    lines.append("")
    if not report["differences"]:
        lines.append("None. Every field the contract describes matches what the scripts "
                     "configure.")
    else:
        lines.append(f"**{report['divergences']} unexplained**, "
                     f"{report['acknowledged']} acknowledged.")
        lines.append("")
        # SAID IN WORDS, because the counts alone invite the wrong reading once the unexplained
        # count reaches zero. "0 unexplained" is not "production matches the contract" — an
        # acknowledgement says why a difference is there, not that it went away.
        if not report["divergences"]:
            lines.append(
                f"Every difference now carries a recorded decision. Production still differs "
                f"from the contract in **{report['stillDiffers']}** places — that is the point "
                f"of the acknowledgements, not something they undo. Each row below says which "
                f"side is authoritative and why.")
            lines.append("")
        lines.append("| Tier | Field | Azure | Contract | | Why |")
        lines.append("|---|---|---|---|---|---|")
        for d in report["differences"]:
            mark = "acknowledged" if d.classification == ACKNOWLEDGED else "**unexplained**"
            lines.append(f"| `{d.tier}` | `{d.field}` | `{d.azure}` | `{d.contract}` | "
                         f"{mark} | {d.note or '—'} |")
    lines.append("")

    lines.append("## Deployed, and not modelled by the contract")
    lines.append("")
    lines.append("| Container app | Why it is out of the tier model |")
    lines.append("|---|---|")
    for d in report["not_modelled"]:
        lines.append(f"| `{d.tier}` | {OUT_OF_SCOPE.get(d.tier, d.note)} |")
    lines.append("")

    lines.append("## What this comparison cannot see")
    lines.append("")
    lines.append("A clean row above means the SCRIPTS agree with the contract. It does not mean "
                 "the running estate does.")
    lines.append("")
    for what, why in sorted(report["unverifiable"].items()):
        lines.append(f"- **{what}** — {why}")
    lines.append("")
    return "\n".join(lines)


def splice(block: str) -> tuple[str, bool]:
    text = TARGET.read_text()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit(
            f"{TARGET.name}: markers not found. Add\n  {BEGIN} -->\n  {END}\n"
            f"around the generated section first.")
    head = text[i:text.index("-->", i) + 4]
    new = f"{head}\n\n{block}\n"
    return text[:i] + new + text[j:], text[i:j] != new


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stdout", action="store_true", help="print the block, write nothing")
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args()

    block = build()
    if args.stdout:
        print(block)
        return 0

    text, changed = splice(block)
    if args.check:
        if changed:
            print("packaging/docs/azure-parity.md is STALE — run "
                  "`python scripts/gen_azure_parity.py` and commit the result.", file=sys.stderr)
            return 1
        print("packaging/docs/azure-parity.md is current")
        return 0
    if not changed:
        print("azure parity unchanged")
        return 0
    TARGET.write_text(text)
    print(f"regenerated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
