// "Why it matters" — the human consequence of failing each WCAG success criterion:
// who is blocked and how. Shown on every coverage tile so the stakes are concrete.
// One concise line per criterion (all 87).
export const WHY = {
  '1.1.1': 'Screen-reader users can’t perceive images, charts or icons.',
  '1.2.1': 'Deaf or blind users get nothing from media with no text alternative.',
  '1.2.2': 'Deaf and hard-of-hearing users can’t follow the spoken content.',
  '1.2.3': 'Blind users miss visual-only information in the video.',
  '1.2.4': 'Deaf users can’t follow live audio without real-time captions.',
  '1.2.5': 'Blind users miss on-screen action the audio doesn’t describe.',
  '1.2.6': 'Deaf users who rely on sign language can’t access the audio.',
  '1.2.7': 'Blind users miss detail when pauses are too short to describe.',
  '1.2.8': 'Deaf-blind users need a full text alternative to the media.',
  '1.2.9': 'Deaf users can’t access live audio-only broadcasts.',
  '1.3.1': 'Screen-reader users lose structure — headings, lists, tables, labels.',
  '1.3.2': 'Screen readers announce content out of order, breaking meaning.',
  '1.3.3': 'Blind users can’t follow “click the round button” instructions.',
  '1.3.4': 'Users who can’t rotate their device are locked out.',
  '1.3.5': 'Users with cognitive disabilities lose autofill help on forms.',
  '1.3.6': 'Assistive tech can’t adapt icons and regions to user needs.',
  '1.4.1': 'Colourblind users miss errors, links or states shown by colour only.',
  '1.4.2': 'Screen-reader users can’t hear over auto-playing audio.',
  '1.4.3': 'Low-vision users can’t read low-contrast text.',
  '1.4.4': 'Low-vision users can’t enlarge text without losing content.',
  '1.4.5': 'Low-vision users can’t resize or restyle text locked in images.',
  '1.4.6': 'Users with low vision need 7:1 contrast to read comfortably.',
  '1.4.7': 'Hard-of-hearing users can’t separate speech from background noise.',
  '1.4.8': 'Users with dyslexia or low vision can’t adapt text blocks to read.',
  '1.4.9': 'Low-vision users can’t restyle any text rendered as an image.',
  '1.4.10': 'Zoom and small-screen users get two-direction scrolling.',
  '1.4.11': 'Low-vision users can’t see buttons, icons or focus outlines.',
  '1.4.12': 'Users who increase spacing lose clipped or overlapping text.',
  '1.4.13': 'Tooltips and popovers vanish or trap low-vision / keyboard users.',
  '2.1.1': 'Keyboard-only and switch users can’t operate the control.',
  '2.1.2': 'Keyboard users get stuck and can’t move past a component.',
  '2.1.3': 'Keyboard-only users can’t reach every function.',
  '2.1.4': 'Speech-input users trigger shortcuts by accident.',
  '2.2.1': 'Users who need more time are cut off mid-task.',
  '2.2.2': 'Moving content distracts or blocks users who can’t pause it.',
  '2.2.3': 'Users with disabilities are pressured by time limits.',
  '2.2.4': 'Pop-ups disrupt users who can’t react quickly.',
  '2.2.5': 'Users lose their work when a session times out.',
  '2.2.6': 'Users aren’t warned before inactivity erases their data.',
  '2.3.1': 'Flashing content can trigger seizures.',
  '2.3.2': 'Any flashing risks seizures for photosensitive users.',
  '2.3.3': 'Motion triggers nausea for users with vestibular disorders.',
  '2.4.1': 'Screen-reader and keyboard users re-hear nav on every page.',
  '2.4.2': 'Users can’t tell pages or documents apart in assistive tech.',
  '2.4.3': 'Keyboard users tab through the page in a confusing order.',
  '2.4.4': 'Screen-reader users hear “click here” with no meaning.',
  '2.4.5': 'Users who can’t navigate one way have no alternative.',
  '2.4.6': 'Screen-reader users can’t scan vague headings and labels.',
  '2.4.7': 'Keyboard users can’t see where they are on the page.',
  '2.4.8': 'Users lose track of where they are in a large site.',
  '2.4.9': 'Screen-reader users scanning links alone get no context.',
  '2.4.10': 'Users can’t navigate long content without section headings.',
  '2.4.11': 'Keyboard users lose the focused element behind overlays.',
  '2.4.12': 'Any covering of the focus point disorients keyboard users.',
  '2.4.13': 'Low-vision keyboard users can’t see a faint focus indicator.',
  '2.5.1': 'Users who can’t do multi-point or path gestures are blocked.',
  '2.5.2': 'Tremor users can’t recover from an accidental tap.',
  '2.5.3': 'Speech-input users can’t activate a control by its visible name.',
  '2.5.4': 'Users who can’t tilt or shake their device are blocked.',
  '2.5.5': 'Tremor and touch users miss small tap targets.',
  '2.5.6': 'Users switching between keyboard, touch and mouse get blocked.',
  '2.5.7': 'Tremor users can’t complete drag-only actions.',
  '2.5.8': 'Touch and tremor users mis-tap small targets.',
  '3.1.1': 'Screen readers mispronounce the page in the wrong language.',
  '3.1.2': 'Screen readers mispronounce foreign-language passages.',
  '3.1.3': 'Users with cognitive disabilities hit undefined jargon.',
  '3.1.4': 'Users can’t expand unfamiliar abbreviations.',
  '3.1.5': 'Users with lower literacy can’t follow complex text.',
  '3.1.6': 'Screen-reader users misunderstand ambiguous pronunciations.',
  '3.2.1': 'Unexpected changes on focus disorient screen-reader users.',
  '3.2.2': 'Forms that change on input surprise and trap users.',
  '3.2.3': 'Users with cognitive disabilities re-learn each page’s nav.',
  '3.2.4': 'Inconsistent icons or labels confuse cognitive-disability users.',
  '3.2.5': 'Automatic changes disorient users who need control.',
  '3.2.6': 'Users can’t reliably find help when they get stuck.',
  '3.3.1': 'Users can’t tell which field has an error or why.',
  '3.3.2': 'Users can’t tell what a form field expects.',
  '3.3.3': 'Users get an error but no way to fix it.',
  '3.3.4': 'Users can’t catch costly mistakes before submitting.',
  '3.3.5': 'Users get no context-sensitive help to complete a task.',
  '3.3.6': 'Any reversible submission lacks a safety check.',
  '3.3.7': 'Users with memory or motor issues re-enter the same data.',
  '3.3.8': 'Users who can’t solve puzzles or recall can’t log in.',
  '3.3.9': 'Any cognitive login test blocks some users entirely.',
  '4.1.1': 'Broken markup makes assistive tech misread the page.',
  '4.1.2': 'Assistive tech can’t identify or operate custom controls.',
  '4.1.3': 'Screen-reader users miss live updates like “saved” or errors.',
}
