// Run from frontend: node e2e/app-panels-styling.fixture.mjs
// Actual primary screen components with deterministic empty/error telemetry.
import { createServer } from 'vite'
import react from '@vitejs/plugin-react'
import { chromium, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
const names=[...(readFileSync('src/api.js','utf8')+readFileSync('src/acrApi.js','utf8')).matchAll(/export\s+(?:async\s+)?(?:const|function)\s+(\w+)/g)].map(x=>x[1])
const fixtures={getConfig:{},getScanLocations:{locations:{}},getWorkerReplicas:{},listAcrReports:{reports:[]},getAdminAnalytics:{scans:0,docs:0,review_pending:0,by_source:{},recent_scans:[]},getAdminActivity:{workflows:[],jobs:[],summary:{}},getWorkerCapacity:{apps:[],available:false}}
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import Integrations from '/src/Integrations.jsx';import Discover from '/src/Discover.jsx';import Assess from '/src/AssessSummary.jsx';import Operations from '/src/AdminLiveTraffic.jsx';import {AdminInsights} from '/src/AdminInsights.jsx';import Conformance from '/src/AcrWorkspace.jsx';import '/src/styles.css';
const me={role:'admin',email:'styling@example.test'};const panel=new URLSearchParams(location.search).get('panel');const populated=new URLSearchParams(location.search).get('state')==='populated';const files=populated?[{file:'LongDocumentName'.repeat(12)+'.docx',source:'sharepoint',status:'analysed',issues:[]}]:[];const sources=populated?[{id:'sharepoint',type:'sharepoint',name:'LongSourceTenantName'.repeat(8)}]:[];const components={sources:<Integrations sources={sources} files={files} me={me} hasSPToken={populated}/>,discover:<Discover sources={sources} files={files} me={me} onScan={()=>{}}/>,assess:<Assess files={[{file:'LongDocumentName'.repeat(15)+'.docx',status:'analysed',issues:[{wcag:'SC_1_1_1',severity:'SERIOUS'}]}]} criteria={new Set(['1.1.1'])} cap={{docx:{'1.1.1':'assisted'}}} assessment={{docx:{'1.1.1':'auto'}}} run={{id:'styling-assess',status:'done'}}/>,operations:<Operations me={me}/>,analytics:<AdminInsights me={me}/>,conformance:<Conformance/>};createRoot(document.getElementById('root')).render(<main className="app">{components[panel]}</main>);`
const server=await createServer({configFile:false,root:process.cwd(),plugins:[{name:'panel-styling-audit',enforce:'pre',resolveId(id){if(/(?:^|\/)(?:api|acrApi)(?:\.js)?$/.test(id))return '\0styling-api';if(id==='/panels-styling.jsx'||id===process.cwd()+'/panels-styling.jsx')return process.cwd()+'/panels-styling.jsx'},load(id){if(id==='\0styling-api')return names.map(n=>n==='openAdminActivityStream'?`export const ${n}=()=>({close(){}});`:`export const ${n}=async()=>(${JSON.stringify(Object.hasOwn(fixtures,n)?fixtures[n]:{})});`).join('\n');if(id===process.cwd()+'/panels-styling.jsx')return entry},configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url.startsWith('/panels-styling?')){res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/panels-styling','<html><div id="root"></div><script type="module" src="/panels-styling.jsx"></script></html>'))}else next()})}},react()],server:{host:'127.0.0.1',port:0}})
await server.listen();const browser=await chromium.launch({headless:true,...(process.env.ACP_E2E_CHROMIUM?{executablePath:process.env.ACP_E2E_CHROMIUM}:{})})
try{const page=await browser.newPage({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:')?route.continue():route.abort())
for(const key of ['sources','sources-populated','discover','discover-populated','assess','operations','analytics','conformance']){const panel=key.replace('-populated','');const state=key.endsWith('-populated')?'populated':'empty';for(const width of [1280,640,390,320]){await page.setViewportSize({width,height:900});await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/panels-styling?panel=${panel}&state=${state}`);await expect(page.locator('main')).not.toBeEmpty();await page.waitForTimeout(200);const overflow=await page.evaluate(()=>({width:innerWidth,actual:document.documentElement.scrollWidth}));if(overflow.actual>width)console.log(await page.locator('*').evaluateAll(nodes=>nodes.filter(el=>el.getBoundingClientRect().right>innerWidth).map(el=>({tag:el.tagName,class:el.className,text:el.textContent.slice(0,80),right:el.getBoundingClientRect().right})).slice(-15)));expect(overflow.actual,`${panel} page overflow at ${width}`).toBeLessThanOrEqual(width);await page.screenshot({path:`/tmp/acp-panel-styling-${key}-${width}.png`,fullPage:true});console.log(`${key} ${width}: layout passes`)}}expect(errors).toEqual([])}finally{await browser.close();await server.close()}
