import {createServer} from 'vite'
import react from '@vitejs/plugin-react'
import {chromium,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
const names=[...readFileSync('src/api.js','utf8').matchAll(/export\s+(?:async\s+)?(?:const|function)\s+(\w+)/g)].map(m=>m[1])
const app=`import React from 'react';import {createRoot} from 'react-dom/client';import Card from '/src/RemediationWaterfallCard.jsx';import '/src/styles.css';const steps=['primary','fallback_1','fallback_2'].map((step_id,position)=>({step_id,position,configured:true,enabled:true,provider:'Recorded provider',model:'ExactModel'+position+'LongIdentity'.repeat(8),attempt_ids:[]}));createRoot(document.getElementById('root')).render(<main style={{padding:12}}><Card snapshot={{scan_id:'s',batch_id:'r',terminal:true,state:'completed',fixes:{verified:4},review:{items:2}}} activity={{view:{available:true,ai_enabled:true,run_graph:{contract_version:'remediation-run-graph.v1',coverage:'complete',chain_version:1,steps,attempts:[]}}}} /></main>);`
const server=await createServer({configFile:false,root:process.cwd(),define:{'import.meta.env.VITE_SIM':JSON.stringify('false'),'import.meta.env.VITE_API':JSON.stringify('http://127.0.0.1:5192')},plugins:[{name:'fixture',enforce:'pre',resolveId(id){if(id==='./api.js'||id.endsWith('/src/api.js'))return '\0fixture-api';if(id==='/drawer-fixture.jsx')return process.cwd()+'/drawer-fixture.jsx'},load(id){if(id==='\0fixture-api')return names.map(n=>`export const ${n}=${n==='getRealtimeStreamRequest'?'()=>({headers:{}})':'async()=>({available:false})'};`).join('\n');if(id===process.cwd()+'/drawer-fixture.jsx')return app},configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url==='/drawer-fixture'){res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml(req.url,'<div id="root"></div><script type="module" src="/drawer-fixture.jsx"></script>'))}else next()})}},react()],server:{host:'127.0.0.1',port:5192,strictPort:true}})
await server.listen();const browser=await chromium.launch({channel:'chrome',headless:true})
try{
const page=await browser.newPage();const errors=[],reads=[];page.on('pageerror',e=>errors.push(e.message))
await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.pathname.includes('/metrics')){reads.push(url.searchParams.get('stage'));return route.fulfill({json:{contract_version:'waterfall-drawer-metrics.v1',scan_id:'s',batch_id:'r',scope:Object.fromEntries(['stage','provider','model'].map(k=>[k,url.searchParams.get(k)])),mode:'recorded',contribution:{title:'Recorded attempt outcomes',unit:'attempts',basis:'Settled attempts, not proposals or findings',rows:[{id:'usable',label:'Validated usable',value:4}]},pace:{value:2,observedSeconds:120,unit:'recorded completions/min',windowLabel:'Final recorded 60 seconds'},trend:{unit:'recorded completions/min',bucketLabel:'60-second buckets',timeZone:'UTC',points:[{timestamp:'2026-09-09T12:00:00Z',value:1},{timestamp:'2026-09-09T12:01:00Z',value:2}]},spend:{rows:[],reason:'Cost not recorded'}}})}if(url.pathname.includes('/insights/'))return route.fulfill({json:{scan_id:'s',batch_id:'r',attempts:[],proposals:[],review_receipts:[]}});return url.origin==='http://127.0.0.1:5192'?route.continue():route.abort()})
for(const width of [1280,768,390,320]){
await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:5192/drawer-fixture')
for(const [index,stage] of ['primary','fallback_1','fallback_2'].entries()){
const button=page.locator('.wf-graph-node').filter({hasText:`ExactModel${index}`});await button.click();await expect(page.getByText('Recorded attempt outcomes',{exact:true})).toBeVisible();expect(reads.at(-1)).toBe(stage);expect(await page.locator('.wd-charts .wd-chart').count()).toBe(3);await expect(page.locator('.wf-delta')).toHaveCount(0);expect(await page.getByRole('dialog').evaluate(e=>e.scrollWidth>e.clientWidth)).toBe(false)
await page.getByRole('tab',{name:'Attempts',exact:true}).click();await expect(page.locator('.wd-chart')).toHaveCount(0);await page.getByRole('tab',{name:'Evidence',exact:true}).click();await expect(page.getByText('Spending for this run',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Overview',exact:true}).click();await expect(page.getByText('Recorded attempt outcomes',{exact:true})).toBeVisible();await page.screenshot({path:`/tmp/waterfall-drawer-${stage}-${width}.png`});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await expect(button).toBeFocused()
}await expect(page.getByText('Where your findings stand')).toHaveCount(0)
}if(errors.length)throw Error(errors.join('\n'));console.log('Integrated primary and both fallbacks passed at1280/768/390/320; exact scopes, tabs, Escape/focus return, no overflow/errors.')
}finally{await browser.close();await server.close()}
