"""Guided manual test plans and their completeness (PRD §14, §15).

WHAT THIS MODULE DECIDES. One question, asked by two callers who must not disagree: **is the
manual evaluation of this criterion finished?** The criterion screen asks it to tell a tester what
is left; `acr_validation` asks it to decide whether the report may publish. Both read this, so a
plan cannot look finished on the screen and unfinished at the gate.

THE SEAM PHASE 1 LEFT. `acr_validation.validate()` already takes `manual_plan_status: dict[str,
bool]` and already defines the `incomplete_manual_test_plan` blocker — Phase 1 built the socket and
passed `{}`, so the category produced no rows rather than pretending to know. This module is what
finally plugs into it. Nothing in the validation rules changes.

WHY A PLAN IS NOT COMPLETE WHEN ITS STEPS ARE ANSWERED. Three things are required, and the two
beyond "every step has an outcome" are the ones that make the evidence reproducible (PRD §4.5):

  1. every step of the plan has a recorded outcome,
  2. the tester is named,
  3. every metadata field the plan DECLARES it needs is present.

(3) is per-plan rather than global on purpose. A screen-reader plan needs the AT name and version;
a viewport-reflow plan does not, and demanding one trains people to type "n/a" — the same
reasoning the metadata form uses for advisory fields. The plan catalog declares its own `needs`.

WHAT THIS MODULE WILL NOT DO. It never decides a conformance status, and completing a plan is not
a pass: `result` records what the tester OBSERVED, and a plan can be complete with a failing step.
"Every step answered" and "the criterion conforms" are different facts, and conflating them is how
a checklist becomes a rubber stamp. `acr_rules` remains the only place a status is derived.

PURE FUNCTIONS OVER RECORDS, no IO — same contract as acr_rules and acr_freshness, and pinned by
test_acr_no_regression.test_the_rule_modules_stay_free_of_io.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from acr_catalog import NOT_APPLICABLE

CATALOG_PATH = Path(__file__).resolve().parent.parent / "config" / "acr-manual-test-plans.json"

# What a tester can record for a step. Deliberately the same vocabulary acr_model uses for
# evidence results, so a plan outcome and the evidence it produces cannot drift apart.
STEP_PASS = "pass"
STEP_FAIL = "fail"
STEP_BLOCKED = "blocked"
STEP_NOT_APPLICABLE = "not_applicable"
STEP_OUTCOMES = frozenset({STEP_PASS, STEP_FAIL, STEP_BLOCKED, STEP_NOT_APPLICABLE})

# A step that was answered at all — every outcome counts, including `fail`. Completeness is about
# whether the tester LOOKED, never about what they found.
ANSWERED = STEP_OUTCOMES


@lru_cache(maxsize=1)
def catalog() -> dict:
    """The plan catalog as generated by scripts/gen_acr_plan_catalog.py."""
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def all_plans() -> list[dict]:
    return list(catalog()["plans"])


def plan(plan_id: str) -> dict | None:
    for p in catalog()["plans"]:
        if p["plan_id"] == plan_id:
            return p
    return None


def plans_for_criterion(criterion_num: str) -> list[dict]:
    """Every plan that exercises this criterion, in catalog order."""
    ids = set(catalog()["criterion_to_plans"].get(criterion_num, []))
    return [p for p in catalog()["plans"] if p["plan_id"] in ids]


def required_plan_ids(criterion_num: str) -> set[str]:
    return set(catalog()["criterion_to_plans"].get(criterion_num, []))


def step_count(plan_id: str) -> int:
    p = plan(plan_id)
    return len(p["steps"]) if p else 0


def missing_metadata(plan_id: str, instance: dict) -> list[str]:
    """Which of the plan's DECLARED needs this instance has not recorded.

    Reads `needs` from the catalog rather than a list in this module: a second list is how a
    screen ends up accepting a plan the publish gate refuses.
    """
    p = plan(plan_id)
    if not p:
        return []
    env = instance.get("environment") or {}
    return [f for f in p["needs"] if not str(env.get(f) or "").strip()]


def instance_complete(instance: dict) -> tuple[bool, str]:
    """Is this ONE plan instance finished? Returns (complete, why-not).

    The reason string is rendered verbatim to the tester, so it says what to do next rather than
    naming a rule.
    """
    plan_id = instance.get("plan_id") or ""
    p = plan(plan_id)
    if not p:
        return False, f"{plan_id or 'this plan'} is not in the plan catalog"

    steps = instance.get("steps") or {}
    total = len(p["steps"])
    answered = [i for i in range(total) if str(steps.get(str(i), "") or "") in ANSWERED]
    if len(answered) < total:
        left = total - len(answered)
        return False, f"{left} of {total} steps still have no recorded outcome"

    if not str(instance.get("tester") or "").strip():
        return False, "no tester is named on this run"

    missing = missing_metadata(plan_id, instance)
    if missing:
        joined = ", ".join(missing)
        verb = "they are" if len(missing) > 1 else "it is"
        return False, f"this plan records {joined} and {verb} not filled in"

    return True, ""


def criterion_complete(criterion_num: str, instances: list[dict],
                       has_human_evidence: bool = False) -> tuple[bool, str]:
    """Is the manual evaluation of this criterion finished?

    THE PLAN CATALOG IS STRUCTURE, NOT A GATE, and the distinction is deliberate. A criterion is
    manually evaluated if it has a complete plan run OR live human evidence recorded any other
    way. An expert who ran a thorough keyboard sweep and recorded it through the evidence form has
    genuinely evaluated the criterion; refusing to count that would make the product demand
    PROCESS compliance in place of evidence, and PRD §4.1 is "evidence before claims", not
    "checklists before claims".

    What still blocks, and it is the case that matters: a plan somebody STARTED and left
    unfinished. That is a half-done evaluation being carried into a published conformance claim,
    which is exactly what PRD §15's category exists to catch. A criterion with no human evidence
    at all is already blocked by acr_validation's own missing-evidence and unapproved categories,
    so nothing is lost by not duplicating that judgement here.

    Where a criterion IS covered by two plans, both must finish — running one of two and calling
    the criterion evaluated is the gap that mapping to a LIST exists to prevent. But that applies
    to plans a tester actually began; it is not a demand that every plan be started.

    `has_human_evidence` is passed in rather than derived: this module is pure functions over
    records (test_the_rule_modules_stay_free_of_io), and acr_rules already owns that judgement.
    """
    required = required_plan_ids(criterion_num)
    if not required:
        return True, ""

    by_plan: dict[str, list[dict]] = {}
    for inst in instances:
        if inst.get("criterion_num") == criterion_num:
            by_plan.setdefault(inst.get("plan_id") or "", []).append(inst)

    # Unfinished runs block whatever else exists — a started plan is a commitment to finish it.
    outstanding: list[str] = []
    for plan_id in sorted(required):
        runs = by_plan.get(plan_id, [])
        if runs and not any(instance_complete(r)[0] for r in runs):
            _, why = instance_complete(runs[0])
            outstanding.append(f"{plan_id}: {why}")
    if outstanding:
        return False, "; ".join(outstanding)

    # Otherwise: a complete run, or human evidence recorded some other way, finishes the job.
    if any(instance_complete(r)[0] for runs in by_plan.values() for r in runs):
        return True, ""
    if has_human_evidence:
        return True, ""

    not_started = sorted(pid for pid in required if not by_plan.get(pid))
    return False, ("no human has evaluated this criterion — run "
                   + " or ".join(not_started) + ", or record a manual result directly")


def manual_plan_status(criteria: list[dict], instances: list[dict],
                       human_evidence: set[str] | None = None) -> dict[str, bool]:
    """The `manual_plan_status` map `acr_validation.validate()` has taken since Phase 1.

    Only criteria the report treats as applicable appear. A criterion marked inapplicable in the
    workspace is triage, not a conformance decision (Phase 2), and does not acquire a manual-plan
    obligation it can then fail.
    """
    out: dict[str, bool] = {}
    for crit in criteria:
        num = crit.get("criterion_num")
        if not num:
            continue
        if crit.get("applicable") is False:
            continue
        # A criterion DECIDED "Not Applicable" has been humanly evaluated: the decision IS the
        # evaluation, and PRD §10 already requires an explanation for it (acr_validation enforces
        # the remarks). Demanding a completed test plan on top would ask someone to run the
        # live-media captions plan against a product that has no live audio — and that plan's own
        # text says an empty inventory is a Not Applicable decision, not a run.
        #
        # Found by Phase 4's publish test: a report whose criteria were all decided Not Applicable
        # with explanations was blocked by 55 incomplete-plan rows, while acr_plans' own docstring
        # claimed it did not duplicate acr_validation's evidence judgement. It did.
        if crit.get("final_status") == NOT_APPLICABLE:
            continue
        out[num] = criterion_complete(num, instances,
                                      num in (human_evidence or set()))[0]
    return out


def progress(criterion_num: str, instances: list[dict],
             has_human_evidence: bool = False) -> dict:
    """What the criterion screen renders: per-plan state for one criterion."""
    rows = []
    for p in plans_for_criterion(criterion_num):
        runs = [i for i in instances
                if i.get("criterion_num") == criterion_num and i.get("plan_id") == p["plan_id"]]
        complete = any(instance_complete(r)[0] for r in runs)
        why = "" if complete else (instance_complete(runs[0])[1] if runs else "not started")
        answered = 0
        if runs:
            steps = runs[0].get("steps") or {}
            answered = sum(1 for k in range(len(p["steps"]))
                           if str(steps.get(str(k), "") or "") in ANSWERED)
        rows.append({
            "plan_id": p["plan_id"],
            "title": p["title"],
            "total_steps": len(p["steps"]),
            "answered_steps": answered,
            "started": bool(runs),
            "complete": complete,
            "blocking_reason": why,
            "needs": list(p["needs"]),
        })
    done, why = criterion_complete(criterion_num, instances, has_human_evidence)
    return {"criterion_num": criterion_num, "plans": rows, "complete": done,
            "blocking_reason": why,
            # Stated on every response so a screen cannot quietly imply otherwise.
            "note": "Completing a plan records what a tester observed. It is not a pass and does "
                    "not select a conformance status."}
